### ISSUE TITLE
MicroProfile Specification Review further feedback on the template

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#11]
**Specification issue template**

Log any comments on the Spec release process and templates

**Comment by aeiras** [comment]
@Emily-Jiang, 

Let's add 

- the email draft [[Voting email](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit)]  on the last step to help that MicroProfile use the template as well. 

- can you also create a short draft to be used by those who will send an email to the EMO?  You can use MPWG folder [voting](https://drive.google.com/drive/u/0/folders/1xnd4qPATbS_Ptbl2wAWYMBYOYFG6c7QO)

after the drafts have been reviewed by more MicroProfilers, we will import them to the MPWG repo under documentation and those links will be updated in the template above. 

:)

**Comment by aeiras** [comment]
Also, let's drop the Specification committee mentions and just use the Steering committee for everything. 
Kevin and I via the email draft had a nice exchange on this, it makes no sense to even mention the spec committee. We combined all committees to be 1, steering. Let's own that!  

Thank you for the push on this!

**Comment by Emily-Jiang** [comment]
@aeiras I don't think the emailing to EMO and PMC needs to bear the name of MP Steering committee as the person who sent the emails are not necessarily in the committee. The other thing is that this is purely from a spec point of view, not even spec committee. It is a group of people.

**Comment by Emily-Jiang** [comment]
I am going to repurpose this issue for further discussion on the process and open an issue just tracking the release process for MP Metrics 3.0.

**Comment by aeiras** [comment]
that makes sense Emily. I didn't know that part. good to learn that :) Thanks!

**Comment by Emily-Jiang** [comment]
@aeiras can you add your feedback on the process or template on this issue instead of putting your thoughts on the release review issue?

**Comment by Emily-Jiang** [comment]
In order not to confuse votes, can you move your comments https://github.com/microprofile/microprofile-wg/issues/9#issuecomment-731426805 in this issue?

**Comment by aeiras** [comment]
Sure Emily, here it goes:

We forgot to include the final step, the Result Ballot notification after the initiated ballot is sent.
 https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit

I am running short of time, given that I am off next-week. I don't want to touch the template in case my rushing causes mistakes. Thanks for the help Emily.

**Comment by Emily-Jiang** [comment]
> Sure Emily, here it goes:
> 
> We forgot to include the final step, the Result Ballot notification after the initiated ballot is sent.
> https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit
> 
> I am running short of time, given that I am off next-week. I don't want to touch the template in case my rushing causes mistakes. Thanks for the help Emily.

Thanks @aeiras ! I have got a [PR](https://github.com/microprofile/microprofile-wg/pull/16) already to address your comment. Would you like to review it? Enjoy your vacation!

**Comment by aeiras** [comment]
Hola Emily, 

the template link needs to be added to the new MPWG page under MPSP section
What is missing to provide us with the final link? Thanks for the reply! : )

I have no further input on what currently is. I expect the #ossDOERs to provide ongoing feedback as they do!

**Comment by Emily-Jiang** [comment]
Which issue should I add the links under?

**Comment by aeiras** [comment]
https://docs.google.com/document/d/1Th7O12AspPUWvudPVSTIZnUXXtyGVxDw-YOzUQyQMIY/edit

added you via comments in the document. Thanks Emily!

**Comment by Emily-Jiang** [comment]
ok, added! Thanks @aeiras !
