### ISSUE TITLE
MicroProfile OpenAPI 3.0 Specification Review

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#110]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-spec/3.0/microprofile-openapi-spec-3.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-spec/3.0/microprofile-openapi-spec-3.0.html)
   - [x] [API Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-api/3.0/microprofile-openapi-api-3.0-javadoc.jar) | [SPI Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1550/org/eclipse/microprofile/openapi/microprofile-openapi-spi/3.0/microprofile-openapi-spi-3.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-api/3.0/microprofile-openapi-api-3.0.jar) | [SPI Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-spi/3.0/microprofile-openapi-spi-3.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1559/org/eclipse/microprofile/openapi/microprofile-openapi-tck/3.0/microprofile-openapi-tck-3.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-open-api-3.0/
   - [x] An apidocs directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request](https://github.com/eclipse/microprofile-open-api/issues/501)
<p>

- [ ] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/openapi-3.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/155) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by radcortez** [comment]
I think we need to reroll this release.

This is still using the old MP Parent version and the TCK javadocs are using the EF Spec License and not the TCK License.

**Comment by JanWesterkamp-iJUG** [comment]
On the title page of the spec documents there is the role of the Spec Lead added to the author's name: Arthur De Magalhaes (Spec Lead)

May be we should remove this (in the next release) as it does not reflect the current status of this role - Emily creates this version ;-)

This is by the way the only spec, where it's done this way...

**Comment by Emily-Jiang** [comment]
@JanWesterkamp-iJUG yes, I will do a service release to remove that wording (Spec Lead). The wording was there since the very beginning.
