### ISSUE TITLE
[MP Calendar Update] During the End of the Year Holiday

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#113]
On Today's community call (11/23) it was discussed and agreed that the MP calendar will be adjusted as follows:
https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles

 Last 2021 MP call will be completed on December 17th
 First 2022 MP call will start on January 3rd. 

 **tasks Completed**
remove from the calendar:
MP OpenTelemetry
MP Starter
MP Marketing
MP Community
MP Technical
MP Metrics
MP GraphQL
MP Context Propagation

**To do**

- [x] delete the zoom internal events of above events for the holiday period

- [x] Add to 2022 calendar OpenTelemetry

- [ ]  add Steering Committee calls for 2022 (2nd Tuesday of the  quarter)

**Check out the MP Zoom Admin** 

https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Zoom-Admin

**New MP calls are welcomed!** 

Thank you Emily for helping with the Zoom clean-up!

**Comment by aeiras** [comment]
@Emily-Jiang, 

Once you are done with the clean, do you mind sending to the MP Community forum this ticket with the brief update? 

Thanks lots,

**Comment by Emily-Jiang** [comment]
@aeiras I am revisiting this ticket to double check the calendar entries. I noticed the marketing call on 3rd Jan is not on MP calendar. Was it deleted by mistak as I thought we agreed we will start the calls on 3rd Jan. Do you want me or yourself to recreate the calendar entry. By the way, the zoom account still has this meeting scheduled.

**Comment by aeiras** [comment]
Días Emily, 
The first meeting is on the 17th. Community call on the 18th. 
there is nothing to talk on the 3rd. Too soon as many are still away. We always need at least a full week to catch up on stuff before community calls. 
that’s why the community call is not on the 4th. 

in my view no mp calls should happen he first week of January.

**Comment by Emily-Jiang** [comment]
@aeiras I think that was not we agreed in the last call though. Please see what you put in this ticket [here](https://github.com/microprofile/microprofile-wg/issues/113#issue-1061780274).

**Comment by aeiras** [comment]
You are so fantastic, Emily. 

Thank you for checking this stuff. I like when you and I collaborate. :) 

Ok, so the 2 calls that ought to happen that first week are:

1. GraphQL - b/c it is monthly and should not be skipped
2. Technical - MP wishes to release innovation in a Feb release. As such, the priority as 2022 starts is to tackle whatever needs to be talked that has not been resolved via git discussions, PRs or issues. 

The steering cmtee is the 2nd tuesday at the start of the quarter. After it, it follows marketing & community calls. 
Not having a call that 1st week of january doesn't mean that MicroProfilers are not doing stuff. 
As you see how MP marketing started 2021, no call happen that first week. There has never been a valuable call on that week under mktg. Instead, we have noticed that the work on media consecutive schedule for 2022 is tackled + other tasks that are set items.  All of them, do not require a call. :) It is super fun! 

With this, can you please delete Community and add Technical call for January 4th?

I hope this is helpful, questions, please do send them my way. Always happy to clear stuff and just brainstorm if we need to, openly. 

![image](https://user-images.githubusercontent.com/10731224/146223324-23c31f66-1f5f-4faa-9525-6a4e5a3dfabe.png)

**Comment by Emily-Jiang** [comment]
@aeiras it is ok to cancel marketing call on Monday. I was just checking to see whether there was a misunderstanding. As for 4th Jan, I think we will just meet on that day. We will need to discuss the 2022 releases and new specification ideas, perhaps start some retrospective. The call will be recorded. I prefer to keep it community call as in this way, it does not mess up the every other-week meeting pattern.

**Comment by Emily-Jiang** [comment]
I have cancelled the marketing call from zoom and sent an email regarding the meeting cancellation to the googlegroup.

**Comment by aeiras** [comment]
Hola Emily, 
Please connect with John ( currently John is the sole Chair for MP Stewarding the Community & Steering calls) on bring the Community call to the 4th. 
In january, our community will need to select a MicroProfile to help John with the task as Kevin is no longer available. :( 
Summers (AJUG) volunteered early in 2021 to help with Stewering Community and Steering calls. 
Either Summers or Edwin could be AMAZING for that task.  It will depend on their desire to help as well.  

----
Now, if the Community calls stay on the calendar for the 4th (you put it there when it wasn't)  we ought to make sure to send the agenda to the community forum 1 week before that first call, latest the 3rd.  
Doing so will ensure that those back from the holidays are reminded to attend & contribute. 
FYI: There are no MP media calendar schedule reminders set up for 2022 yet. Those reminders will be set by the 2nd week of January and onward. 

---- 
The 2021 Retrospective ought not to happen on the 4th. Please check the git issue where I pulled you, Roberto and Edwin about the spreadsheet with a call to action for brainstorming on how to run it across all MicroProfile areas (Program Plan in focus)  

We wish for more retrospective feedback, not less and not rush :) 
For that, it needs time. The end of January call is preferred given the goal. Recommending such timeline or similar.
