### ISSUE TITLE
MicroProfile Telemetry Creation Review

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#114]
### Background
MicroProfile OpenTracing was based on OpenTracing, which was discontinued. OpenTelemetry is the replacement for OpenTracing. Therefore, MicroProfile needs to adopt OpenTelemetry so that the MicroProfile applications can work with the new Tracer providers.
### Scope
MicroProfile Telemetry will focus on Tracing first. In the future releases, it might adopt loging, metrics.
### Description
MicroProfile Telemetry pulls in OpenTelemetry tracing and integrate with CDI and Jakarta Restful Services. It provides three types of instrumentations:

- Automatic Instrumentation

Jakarta RESTful Web Services (server and client), and MicroProfile REST Clients are automatically enlisted to participate in distributed tracing without code modification as specified in the Tracing API.

- Manual Instrumentation

Explicit manual instrumentation can be added into a MicroProfile application using annotation or programmatic lookup.

- Agent Instrumentation

Implementations are free to support the OpenTelemetry Agent Instrumentation.

### Testing
TCKs will be provided to test the CDI and Jakarta Restful Web Services integration and any new APIs that might be introduced.

More detailed proposal can be found [here](https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/microprofile-telemetry).

**Comment by riferrei** [comment]
I loved this initiative and would help provide support for it.
