### ISSUE TITLE
MicroProfile GraphQL 2.0 Specification Review

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#127]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [ ] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584/org/eclipse/microprofile/graphql/microprofile-graphql-spec/2.0/microprofile-graphql-spec-2.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584/org/eclipse/microprofile/graphql/microprofile-graphql-spec/2.0/microprofile-graphql-spec-2.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584/org/eclipse/microprofile/graphql/microprofile-graphql-api/2.0/microprofile-graphql-api-2.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584/org/eclipse/microprofile/graphql/microprofile-graphql-api/2.0/microprofile-graphql-api-2.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1584/org/eclipse/microprofile/graphql/microprofile-graphql-tck/2.0/microprofile-graphql-tck-2.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-graphql-2.0/
   - [x] An apidocs directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request](https://github.com/eclipse/microprofile-graphql/issues/435)
<p>

- [ ] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/graphql-2.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/254) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) ([more info][here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by radcortez** [comment]
A few comments:

- The TCK Jar is linking to the wrong file
- The Compatible Certification Request references GraphQL `2.0-RC3 and not `2.0`.
- The `master` branch is not updated with the `2.0` release.

These should be resolved before moving the release forward.

**Comment by Emily-Jiang** [comment]
> A few comments:
> 
>     * The TCK Jar is linking to the wrong file
> 
fixed
>     * The Compatible Certification Request references GraphQL `2.0-RC3 and not `2.0`.
> 
fixed
>     * The `master` branch is not updated with the `2.0` release.
> 
I don't believe this is the requirement for this ballot. This 2.0 release was created off `EE9` branch. The GraphQL team can decide whether to create another branch for future releases. The `master` branch might be used for other purpose. If they want to use `master` for future releases, the changes from EE9 would be merged to `master` branch.
> 
> These should be resolved before moving the release forward.

**Comment by radcortez** [comment]
> 
> > ```
> > * The Compatible Certification Request references GraphQL `2.0-RC3 and not `2.0`.
> > ```
> 
> fixed
> 

The issue https://github.com/eclipse/microprofile-graphql/issues/435 still links to:

https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java8-TCKResults.html
https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java11-TCKResults.html
https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java17-TCKResults.html

Which refers [MicroProfile GraphQL 2.0-RC3](https://download.eclipse.org/microprofile/microprofile-graphql-2.0-RC3/microprofile-graphql-spec-2.0-RC3.html)

> > ```
> > * The `master` branch is not updated with the `2.0` release.
> > ```
> 
> I don't believe this is the requirement for this ballot. This 2.0 release was created off `EE9` branch. The GraphQL team can decide whether to create another branch for future releases. The `master` branch might be used for other purpose. If they want to use `master` for future releases, the changes from EE9 would be merged to `master` branch.
> 
> > These should be resolved before moving the release forward.

I can't entirely agree because we explicitly added that step (merge the Jakarta work with `master`) as part of the activities to migrate to Jakarta. It is listed here: https://github.com/eclipse/microprofile-graphql/issues/386 (deliver the changes to both jakarta91-branch and master)

**Comment by Emily-Jiang** [comment]
> > > ```
> > > * The Compatible Certification Request references GraphQL `2.0-RC3 and not `2.0`.
> > > ```
> > 
> > 
> > fixed
> 
> The issue [eclipse/microprofile-graphql#435](https://github.com/eclipse/microprofile-graphql/issues/435) still links to:
> 
> https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java8-TCKResults.html https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java11-TCKResults.html https://openliberty.io/certifications/microprofile/graphql/2.0/22.0.0.4-beta-Java17-TCKResults.html
> 
> Which refers [MicroProfile GraphQL 2.0-RC3](https://download.eclipse.org/microprofile/microprofile-graphql-2.0-RC3/microprofile-graphql-spec-2.0-RC3.html)
> 
The CCR has been using RCx. Not sure what your comments are. The CCR link points to 2.0-RC3 and now I have updated the wording to mention 2.0-RC3. Is this what you meant.
> > > ```
> > > * The `master` branch is not updated with the `2.0` release.
> > > ```
> > 
> > 
> > I don't believe this is the requirement for this ballot. This 2.0 release was created off `EE9` branch. The GraphQL team can decide whether to create another branch for future releases. The `master` branch might be used for other purpose. If they want to use `master` for future releases, the changes from EE9 would be merged to `master` branch.
> > > These should be resolved before moving the release forward.
> 
> I can't entirely agree because we explicitly added that step (merge the Jakarta work with `master`) as part of the activities to migrate to Jakarta. It is listed here: [eclipse/microprofile-graphql#386](https://github.com/eclipse/microprofile-graphql/issues/386) (deliver the changes to both jakarta91-branch and master)

Let me clarify this. The ballot is to verify whether the artifacts we put up on the staging are good to be released. Reviewing the current project progress is good but not mandatory. If any issues are found, they should be noted and feedback to the spec team, which I have done. I disagree this is the valid reason to stop the ballot. As far as I know, it is not in the checklist for release review.

**Comment by dblevins** [comment]
> > > The CCR has been using RCx. Not sure what your comments are. The CCR link points to 2.0-RC3 and now I have updated the wording to mention 2.0-RC3. Is this what you meant.
> > 
> > 
> > That is the issue. The CCR must point to the binaries created by this release and not the ones from another RC. If so, how can we tell these binaries work? (Yes, I know they are the same). This has been the discussion about Compatible Implementations requiring public releases for the APIs (which are not yet available) that cause the chicken-egg problem.
> 
> I think I am confused :(. Are you saying [this](https://github.com/eclipse/microprofile-graphql/issues/435) issue should mention the staged repo for 2.0 release. Where should it point to? The temp sonatype link or non-existing-yet maven repo? As we discussed in the past, CCR was created using RCx, which was agreed. Please see [this]([eclipse/microprofile-rest-client#340](https://github.com/eclipse/microprofile-rest-client/issues/340) for MicroProfile Rest Client release.

What we've documented is that a certification request must be made against the final TCK.  To ensure the final TCK was used and not a snapshot or previous release, the SHA-256 hash of the TCK binary must be mentioned in the certification request:

 - https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc#filing-a-certification-request

I'm not aware of any requirements as to what jars or libraries a library must put *inside* their servers or ship; it can be an RC or even an uber jar of their own making.  There is no chicken-and-egg situation in that regard.  If the implementation can pass the final TCK, their API jar is their business.

Vendors have complete freedom in how they create and ship their software.  The only ask from a specification perspective is "please run the tests again one last time with the proposed final TCK so we have assurance that the TCK binary is perfect."

**Comment by radcortez** [comment]
> What we've documented is that a certification request must be made against the final TCK. 

Exactly. In the linked CCR the referenced MicroProfile GraphQL version is `2.0-RC3`, so that is why I've asked for additional clarification.

> I'm not aware of any requirements as to what jars or libraries a library must put _inside_ their servers or ship; it can be an RC or even an uber jar of their own making.

I'm not totally sure if I agree. We don't have signature tests in the MP TCK's. I know that it may be a long shot, but what if the shipped APIs are changed in such a way that may affect the TCK's run and provide erroneous results?

**Comment by Emily-Jiang** [comment]
> > > > The CCR has been using RCx. Not sure what your comments are. The CCR link points to 2.0-RC3 and now I have updated the wording to mention 2.0-RC3. Is this what you meant.
> > > 
> > > 
> > > That is the issue. The CCR must point to the binaries created by this release and not the ones from another RC. If so, how can we tell these binaries work? (Yes, I know they are the same). This has been the discussion about Compatible Implementations requiring public releases for the APIs (which are not yet available) that cause the chicken-egg problem.
> > 
> > 
> > I think I am confused :(. Are you saying [this](https://github.com/eclipse/microprofile-graphql/issues/435) issue should mention the staged repo for 2.0 release. Where should it point to? The temp sonatype link or non-existing-yet maven repo? As we discussed in the past, CCR was created using RCx, which was agreed. Please see [this]([eclipse/microprofile-rest-client#340](https://github.com/eclipse/microprofile-rest-client/issues/340) for MicroProfile Rest Client release.
> 
> What we've documented is that a certification request must be made against the final TCK. To ensure the final TCK was used and not a snapshot or previous release, the SHA-256 hash of the TCK binary must be mentioned in the certification request:
> 
>     * https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc#filing-a-certification-request
> 
> 
> I'm not aware of any requirements as to what jars or libraries a library must put _inside_ their servers or ship; it can be an RC or even an uber jar of their own making. There is no chicken-and-egg situation in that regard. If the implementation can pass the final TCK, their API jar is their business.
> 
> Vendors have complete freedom in how they create and ship their software. The only ask from a specification perspective is "please run the tests again one last time with the proposed final TCK so we have assurance that the TCK binary is perfect."

When I read the TCK process, it did not occur to me that the TCK jars for CCR must be the Final one. In that paragraph, it did not mention the Final TCK wording etc. Since in the past, we used the identical RC with the final TCK for TCK result, I thought we are using the same process. Hence the confusion. I think we should discuss in the technical call to see whether we have to use the final TCK jar or RC jar and clarify this in the process with the resolution.

**Comment by radcortez** [comment]
In SmallRye CCR's we always used the final original artifacts from the MP release (both APIs and TCKs). In the past, we didn't want to release such SmallRye binaries because they would keep a reference to a temporary repository (the staging repo), but it was required by the WG: https://github.com/microprofile/microprofile-wg/issues/9#issuecomment-737253375

**Comment by Emily-Jiang** [comment]
> In SmallRye CCR's we always used the final original artifacts from the MP release (both APIs and TCKs). In the past, we didn't want to release such SmallRye binaries because they would keep a reference to a temporary repository (the staging repo), but it was required by the WG: [#9 (comment)](https://github.com/microprofile/microprofile-wg/issues/9#issuecomment-737253375)

We discussed this chicken and egg situation and then decided to use RC to release the final spec. I think Kevin meant is to say the impl release needs to be made to public, such as Open Liberty beta driver, which is in maven central.

**Comment by Emily-Jiang** [comment]
> > > In SmallRye CCR's we always used the final original artifacts from the MP release (both APIs and TCKs). In the past, we didn't want to release such SmallRye binaries because they would keep a reference to a temporary repository (the staging repo), but it was required by the WG: [#9 (comment)](https://github.com/microprofile/microprofile-wg/issues/9#issuecomment-737253375)
> > 
> > 
> > We discussed this chicken and egg situation and then decided to use RC to release the final spec. I think Kevin meant is to say the impl release needs to be made to public, such as Open Liberty beta driver, which is in maven central.
> 
> No, I think it is important to reference the proposed final assets for the CI which veryfies compatibility and implementablility, where the CI can do the naming like it wants to do, but the proposed final assets need to be referenced. While there not released at this time (staging only for some time), they need to be put somewhere "forever". The last is fulfilled for the spec assets, if it will be released unchanged. For a clean result, the CI may need to do a (additional, may be final) release against the final destination (maven central) of the spec assets - but the last need to go first.
> 
> Graphically documenting this might be helpful... ;-) May be adding this to the TCK process?

@JanWesterkamp-iJUG please read [this](https://groups.google.com/g/microprofile/c/6v65mBjIXiQ/m/OfM9bLmTBAAJ) thread to understand the concerns.
