### ISSUE TITLE
MicroProfile Metrics 3.0 Specification Review

### ISSUE THREAD

**Issue by donbourne** [microprofile/microprofile-wg#15]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version: MicroProfile Metrics V3.0
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-spec/3.0/microprofile-metrics-spec-3.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-spec/3.0/microprofile-metrics-spec-3.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-api/3.0/microprofile-metrics-api-3.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-api/3.0/microprofile-metrics-api-3.0.jar)
   - [x] [API TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-api-tck/3.0/microprofile-metrics-api-tck-3.0.jar)
   - [x] [REST TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-rest-tck/3.0/microprofile-metrics-rest-tck-3.0.jar)
   - [x] [Optional TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1382/org/eclipse/microprofile/metrics/microprofile-metrics-optional-tck/3.0/microprofile-metrics-optional-tck-3.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-metrics-3.0/
   - [x] An apidocs directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-metrics/issues/623)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/metrics-3.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569302) created by EMO after the email) 
  - [x] A member of Steering/Spec Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
  - [x] Result ballot notification - https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit

**Comment by aeiras** [comment]
hola Don,  @donbourne, 

we forgot to include the final step, the Result Ballot notification after the initiated ballot is sent. 
can you you add the step to Metrics?  https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit

:) thank YOU! the general template needs to be adjusted as well. :)

**Comment by donbourne** [comment]
hey Amelia @aeiras , I've added that to the end per your comment.

**Comment by aeiras** [comment]
Amazing Don, thank you!

**Comment by radcortez** [comment]
+1

**Comment by kwsutter** [comment]
@donbourne I just commented on the CCR that the CI used for the testing needs to be a "permanent" artifact and not just a nightly driver that would be difficult to reproduce in the future.

**Comment by donbourne** [comment]
@kwsutter , we intended for the nightly driver to be stored as a permanent artifact, but messed that up and the driver was deleted.  We've rerun the TCK on a newer driver which we're copying for permanent storage and will update the CCR with that URL once it's in place.

**Comment by donbourne** [comment]
@kwsutter , the problem with the CCR pointing to a non-permanent driver has been resolved.  It now points to a downloadable driver that should be there "permanently".

**Comment by donbourne** [comment]
MP Metrics 3.0 has been released
