### ISSUE TITLE
Evaluate adoption of Jakarta Core Profile

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-wg#160]

**Comment by jclingan** [comment]
The [Jakarta EE Core Profile 10](https://jakarta.ee/specifications/coreprofile/10/) support is planned for MicroProfile 6.0

**Comment by radcortez** [comment]
For older versions, the parent POM included the Jakarta Annotations, and Jakarta Interceptors is being pulled transitively by CDI. There is not much we can do there.

We now list Jakarta Annotations as being part of the platform. For Jakarta Interceptors, it is required by CDI, so we need to include it as well.

The Jakarta Core Profile adoption was added in https://github.com/eclipse/microprofile-parent/pull/62/, so I think this is complete.
