### ISSUE TITLE
MicroProfile Rest Client 2.0 Specification Review

### ISSUE THREAD

**Issue by andymc12** [microprofile/microprofile-wg#18]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/microprofile-rest-client-spec/2.0/microprofile-rest-client-spec-2.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/microprofile-rest-client-spec/2.0/microprofile-rest-client-spec-2.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/microprofile-rest-client-api/2.0/microprofile-rest-client-api-2.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/microprofile-rest-client-api/2.0/microprofile-rest-client-api-2.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/microprofile-rest-client-tck/2.0/microprofile-rest-client-tck-2.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-rest-client-2.0/
   - [x] An [apidocs directory](https://download.eclipse.org/microprofile/staging/microprofile-rest-client-2.0/apidocs/) containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request](https://github.com/eclipse/microprofile-rest-client/issues/295)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/rest-client-2.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569488) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by kwsutter** [comment]
This all looks good.  Just a couple of nits in the CCR.  Thanks!
