### ISSUE TITLE
MicroProfile JWT RBAC 1.2 Specification Review

### ISSUE THREAD

**Issue by sberyozkin** [microprofile/microprofile-wg#19]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1384)
   - [x] [Spec PDF](https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/microprofile-jwt-auth-spec-1.2.pdf)
   - [x] [Spec HTML](https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/microprofile-jwt-auth-spec-1.2.html)
   - [x] [Javadoc](https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/microprofile-jwt-auth-api-1.2-javadoc.jar)
   - [x] [API Jar](https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/microprofile-jwt-auth-api-1.2.jar)
   - [x] [TCK Jar](https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/microprofile-jwt-auth-tck-1.2.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-jwt-auth-1.2/apidocs/
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-jwt-auth/issues/227)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/jwt-rbac-1.2)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569483) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit))

**Comment by radcortez** [comment]
+1

**Comment by Emily-Jiang** [comment]
+1

**Comment by emecas** [comment]
+1

Thanks everybody contributing to this specification!!!!

Note: I have added a PR eclipse/microprofile-jwt-auth#229 directly on the microprofile-jwt-auth spec's repo, fixing some minor typos i found during my review

**Comment by kwsutter** [comment]
> Note: I have added a PR [eclipse/microprofile-jwt-auth#229](https://github.com/eclipse/microprofile-jwt-auth/pull/229) directly on the microprofile-jwt-auth spec's repo, fixing some minor typos i found during my review

Thanks!  Just be aware that this PR would have to be processed *after* this release is complete.  So, the changes would go into the next rev of the JWT spec -- 1.3 or 2.0.

**Comment by juneau001** [comment]
+1 (CJUG Community Vote)

**Comment by acoburn** [comment]
+1 (Community Vote)
