### ISSUE TITLE
MicroProfile Telemetry 1.1 Specification Review

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#196]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1631)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1631/org/eclipse/microprofile/telemetry/tracing/microprofile-telemetry-tracing-spec/1.1/microprofile-telemetry-tracing-spec-1.1.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1631/org/eclipse/microprofile/telemetry/tracing/microprofile-telemetry-tracing-spec/1.1/microprofile-telemetry-tracing-spec-1.1.html)
   - [ ] Javadoc: n/a
   - [ ] API Jar: n/a
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1631/org/eclipse/microprofile/telemetry/tracing/microprofile-telemetry-tracing-tck/1.1/microprofile-telemetry-tracing-tck-1.1.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-telemetry-1.1/tracing/
   - [ ] An apidocs directory containing the javadoc associated with the API jar: n/a
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-telemetry/issues/130)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/telemetry-1.1)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info) [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](add link) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by mtdelgadoa** [comment]
We're updating our release review process by integrating the review checklist directly into your GitHub workflow. This change will enhance our ability to provide more effective feedback within the context of each issue, leading to improved efficiency, collaboration, and the elimination of duplication.

# EMO REVIEW

- PMI Review Record: https://projects.eclipse.org/projects/technology.microprofile/reviews/telemetry-1.1-release-review

## Intellectual Property Management

_To be completed by the EMO._

- [ ] All project code has [copyright and license headers](https://www.eclipse.org/projects/handbook/#ip-copyright-headers) correctly applied. ** EMO will scan the code at their discretion **
- [ ] All distributed third-party content has been vetted by the IP Due Diligence process (i.e., IP Log has been approved)

## Open Source Rules of Engagement

- [x] PMC approval [on the mailing list](https://www.eclipse.org/mhonarc/lists/technology-pmc/msg13295.html)

## Branding and Trademarks

_To be completed by the EMO and PMC._

The following applies when the project has a custom website.

To the best of our knowledge:
- [ ] Project content correctly uses Eclipse Foundation trademarks
- [ ] Project content (code and documentation) does not violate trademarks owned by other organizations

Things to check:
- Project website uses the [project's formal name](https://www.eclipse.org/projects/handbook/#trademarks-website-name) in first and all prominent references 
- Project website includes a [trademark attribution statement](https://www.eclipse.org/projects/handbook/#trademarks-website)
- Project website footers contain all [necessary elements](https://www.eclipse.org/projects/handbook/#trademarks-website-footer)



## Legal Documentation

Required files:

- [ ] License files in all repository roots
- [ ] README
- [ ] CONTRIBUTING (or equivalent)

Recommended files: 

- [ ] NOTICES or equivalent you can use the [Legal Documentation generator](https://www.eclipse.org/projects/tools/documentation.php) available under committer tools
- [ ] CODE_OF_CONDUCT
- [ ] SECURITY 

See examples for [Security file](https://github.com/eclipse-ee4j/.github/blob/main/SECURITY.md) and [Code of Conduct](https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md).

Required elements:

- [ ] ECA is referenced/described

Recommended elements: 

- [ ] Build instructions provided
- [ ] [Security policy](https://www.eclipse.org/security/policy.php) is described

## Metadata (PMI)

_To be completed by the EMO_

- [ ] The formal name, e.g. "Eclipse Foo™", is used in the project title
- [ ] The formal name including appropriate marks (e.g, "™") is used in the first mention in the text of the project description, and scope
- [ ] The project description starts with a single paragraph that can serve as an executive summary
- [ ] Source code repository references are up-to-date
- [ ] Download links and information are up-to-date (see [EF handbook for more information on how-to do this](https://www.eclipse.org/projects/handbook/#resources-downloads))
- [ ] Communication channels listed in the PMI (i.e. public mailing list, forums, etc.)

```

**Comment by mtdelgadoa** [comment]
The Contributing file is missing from the Telemetry repository. Also, please consider adding recommended files (i.e. Code of Conduct and Security) directly in there.

**Comment by Emily-Jiang** [comment]
> The Contributing file is missing from the Telemetry repository. Also, please consider adding recommended files (i.e. Code of Conduct and Security) directly in there.

@mtdelgadoa I have done this PR [here](https://github.com/eclipse/microprofile-telemetry/pull/131). Please confirm whether this is what you are asking. Is this a gate factor for a release or you will be able to accept the ballot? By the way, it was not spotted in the 1.0 release. Please confirm.

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang, I created my (additional) finding here:

https://github.com/eclipse/microprofile-telemetry/issues/132#

**Comment by mtdelgadoa** [comment]
@Emily-Jiang the added files should be enough. However, I'm not able to build the project nor evaluate the 3rd aprty dependencies for some reason. Any pointers?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang the added files should be enough. However, I'm not able to build the project nor evaluate the 3rd aprty dependencies for some reason. Any pointers?

You would not be able to build it as this project has dependency on Config 3.1 that is in staging. You can update [this](https://github.com/eclipse/microprofile-telemetry/blob/main/tracing/pom.xml#L36) line with the version of 3.1-RC2 instead of 3.1 to get this project to build so that you can evaluate the 3rd party dependencies.

**Comment by mtdelgadoa** [comment]
This EMO review has concluded succesfully. Please continue with your release. As a general comment, please consider integrating the [Dash-Licenses tool ](https://github.com/eclipse/dash-licenses) to vet any 3rd party dependencies in your microprofile projects.
