### ISSUE TITLE
MicroProfile OpenAPI 2.0 Specification Review

### ISSUE THREAD

**Issue by phillip-kruger** [microprofile/microprofile-wg#20]
**Specification issue template**

- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389/org/eclipse/microprofile/openapi/microprofile-openapi-spec/2.0/microprofile-openapi-spec-2.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389/org/eclipse/microprofile/openapi/microprofile-openapi-spec/2.0/microprofile-openapi-spec-2.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389/org/eclipse/microprofile/openapi/microprofile-openapi-api/2.0/microprofile-openapi-api-2.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389/org/eclipse/microprofile/openapi/microprofile-openapi-api/2.0/microprofile-openapi-api-2.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1389/org/eclipse/microprofile/openapi/microprofile-openapi-tck/2.0/microprofile-openapi-tck-2.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-open-api-2.0/
   - [x] An [apidocs](https://download.eclipse.org/microprofile/staging/microprofile-open-api-2.0/apidocs/) directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-open-api/issues/459)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/openapi-2.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569605) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by kwsutter** [comment]
The apidocs directory is not displaying the javadoc correctly:  https://download.eclipse.org/microprofile/staging/microprofile-open-api-2.0/apidocs/.  But, your javadoc jar file looks good, so this won't affect my vote.

I also added a couple of comments to the [CCR](https://github.com/eclipse/microprofile-open-api/issues/459).  Nothing major, but should be cleaned up before going final.  Thanks!

**Comment by radcortez** [comment]
I had no issue navigating the javadocs. Maybe a hiccup in the server?

**Comment by kwsutter** [comment]
> I had no issue navigating the javadocs. Maybe a hiccup in the server?

Maybe it's a Firefox issue?  I just tried it with Chrome and everything looks just fine...  Thanks for verifying, @radcortez!
