### ISSUE TITLE
MicroProfile Open Tracing 2.0 Specification Review

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-wg#21]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/org/eclipse/microprofile/opentracing/microprofile-opentracing-spec/2.0/microprofile-opentracing-spec-2.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/org/eclipse/microprofile/opentracing/microprofile-opentracing-spec/2.0/microprofile-opentracing-spec-2.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/org/eclipse/microprofile/opentracing/microprofile-opentracing-api/2.0/microprofile-opentracing-api-2.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/org/eclipse/microprofile/opentracing/microprofile-opentracing-api/2.0/microprofile-opentracing-api-2.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1397/org/eclipse/microprofile/opentracing/microprofile-opentracing-tck/2.0/microprofile-opentracing-tck-2.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-opentracing-2.0/
   - [x] An [apidocs](https://download.eclipse.org/microprofile/staging/microprofile-opentracing-2.0/apidocs/) directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-opentracing/issues/214)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/opentracing-2.0)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569631) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by kwsutter** [comment]
The link for the staged apidocs is not working correctly:  https://download.eclipse.org/microprofile/staging/microprofile-opentracing-2.0/apidocs/

It partially works where I get the three classes identified on the left hand side.  But, the main page has displays a "Not Found" error page.  I have verified that the javadoc jar seems to work just fine.  It's just this staged directory that is not displaying correctly.

I also have a couple of comments on the CCR.  Nothing major to prevent a +1, but these items should be cleaned up before declaring they are final.

**Comment by xstefank** [comment]
> The link for the staged apidocs is not working correctly: https://download.eclipse.org/microprofile/staging/microprofile-opentracing-2.0/apidocs/
> 
> It partially works where I get the three classes identified on the left hand side. But, the main page has displays a "Not Found" error page. I have verified that the javadoc jar seems to work just fine. It's just this staged directory that is not displaying correctly.

It works for me. No Not Founds. Not sure what can be the problem.

> I also have a couple of comments on the [CCR](https://github.com/eclipse/microprofile-opentracing/issues/214). Nothing major to prevent a +1, but these items should be cleaned up before declaring they are final.

CCR was updated according to the requierements.

**Comment by kwsutter** [comment]
> > The link for the staged apidocs is not working correctly: https://download.eclipse.org/microprofile/staging/microprofile-opentracing-2.0/apidocs/
> > It partially works where I get the three classes identified on the left hand side. But, the main page has displays a "Not Found" error page. I have verified that the javadoc jar seems to work just fine. It's just this staged directory that is not displaying correctly.
> 
> It works for me. No Not Founds. Not sure what can be the problem.

Yeah.  Thanks, @xstefank.  As @radcortez pointed out, it might be a Firefox issue...  Works fine on Chrome.  Sorry for the fire drill, but thanks for checking it out.

> 
> > I also have a couple of comments on the [CCR](https://github.com/eclipse/microprofile-opentracing/issues/214). Nothing major to prevent a +1, but these items should be cleaned up before declaring they are final.
> 
> CCR was updated according to the requirements.

Thanks!

**Comment by Emily-Jiang** [comment]
@dblevins @aeiras please cast your vote via the microprofile-wg! You can find the thread [here](https://groups.google.com/g/microprofile/c/w5ykU-Y7P4w).
