### ISSUE TITLE
Include the MicroProfile Specification Process on the website

### ISSUE THREAD

**Issue by waynebeaton** [microprofile/microprofile-wg#22]
AFAICT, the MicroProfile Specification Process is currently only published on the [working group's web site](https://microprofile.io/workinggroup/) as a link to the Google Doc. 

This should be replaced with either a link to the document here, or to a page on the website generated from the ./mpsp.adoc source.

**Comment by aeiras** [comment]
Hola Wayne,

The plan is to update the Projects <https://microprofile.io/projects/> page
on the website. Work has started on the how via another thread in Q4 2020.

While navigating MP 4.0 release, we created templates for most things based
on actions. We will implement the updates with care in Q1.
Thanks,

Amelia Eiras
twitter.com/ameliaeiras
Tribe: http://tomitribe.com      https://tribestream.io
OSS:  http://microprofile.io     https://jakarta.ee

**Comment by aeiras** [comment]
completed. https://microprofile.io/microprofile-specification-process/
