### ISSUE TITLE
2024: Evolve MicroProfile Telemetry

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-wg#229]
Evolve MicroProfile Telemetry to include OpenTelemetry Metrics and OpenTelemetry Logging

**Comment by jclingan** [comment]
Covered during March 19th Steering Commitee meeting. We have made progress here via Telemetry 2.0 release plan vote passing.

**Comment by Emily-Jiang** [comment]
We successfully released MP Telemetry 2.0, part of MP 7.0.
