### ISSUE TITLE
MicroProfile Context Propagation 1.2 Specification Review

### ISSUE THREAD

**Issue by njr-11** [microprofile/microprofile-wg#24]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
  MicroProfile Context Propagation 1.2
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
     https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
     https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.html
   - _project_ is the microprofile specification short project name (config, health, ...)
     context-propagation
   - _version_ is the two digit x.y version of the specification
     1.2
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/)
   - [x] [Spec PDF](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.html)
   - [x] [Javadoc](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-api/1.2/microprofile-context-propagation-api-1.2-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-api/1.2/microprofile-context-propagation-api-1.2.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/service/local/repositories/orgeclipsemicroprofile-1434/content/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-tck/1.2/microprofile-context-propagation-tck-1.2.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-_project_-_version_/
     https://download.eclipse.org/microprofile/staging/microprofile-context-propagation-1.2/
   - [x] An apidocs directory containing the javadoc associated with the API jar.
     https://download.eclipse.org/microprofile/staging/microprofile-context-propagation-1.2/apidocs/
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-context-propagation/issues/209)
<p>

- [ ] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/context-propagation-1.2)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571068) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [ ] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by kwsutter** [comment]
Closing on behalf of @Emily-Jiang and @njr-11.
