### ISSUE TITLE
[Technical Goal 4]: MicroProfile and Jakarta EE alignment

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#32]
MicroProfile and Jakarta EE alignment efforts from CN4J alliance
* Move, Fork, LTS, push vs pull, etc
* Rebase on Jakarta EE 9 and subsequent releases

**Comment by aeiras** [comment]
This ticket is very general. 

The Program Plan 2022 has identified specific goals that need to be imported here. :)  closing it.

**Comment by radcortez** [comment]
Jakarta alignment was released with MP 5.0.
