### ISSUE TITLE
[Trademark] Compatible Logo

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#38]
From the MP markting repo[ issue ](https://github.com/eclipse/microprofile-marketing/issues/268)

[Drive](https://drive.google.com/drive/u/0/folders/1kawjoICH8vuNILCSlPGb_6Sd9oSMTQke)

**Comment by rstjames** [comment]
@aeiras latest logo updates from emerson. Still does not align with the others but ... we can adjust things after if it's won. 
[Microprofile-compatible-logo-options-juy27.pdf](https://github.com/microprofile/microprofile-wg/files/6884114/Microprofile-compatible-logo-options-juy27.pdf)

**Comment by aeiras** [comment]
Thank you, Ryan for working with Emerson to improve the design. It looks better. 

I have dropped the PDF in the [drive](https://drive.google.com/drive/u/0/folders/1unMeyPjVudkheFUKnpWYahAtAkT6An0b)
