### ISSUE TITLE
MicroProfile Member Logo

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#39]
from [[MPWG- design task] MicroProfile Member Banner #269](https://github.com/eclipse/microprofile-marketing/issues/269) 

[Drive](https://drive.google.com/drive/u/0/folders/1bWw-Ytwht4xCzmr618FOAYYwKkjGHEvZ)

**Comment by rstjames** [comment]
@aeiras we are calling the "Compatability" badge a "logo" we should have this task also called a "logo" or "badge". 
NOT "banner" it is confusing what it is.

**Comment by aeiras** [comment]
Good call out, I will fix it. This was a transfer from the other Repo. Thanks Ryan! 🥋

**Comment by aeiras** [comment]
To be discussed during the marketing call and then the community call (with the decision) on how to get this done. 

My recommendation is for any of the members to create a design, submit, & members (steering cmtee) gets to vote on final design. Easy, effortless and simple. 

Ryan, are you ok to add it to the agenda and own the how you think we could do this if above recommendation is not efficient for the mark? Thank you, @rstjames!

**Comment by aeiras** [comment]
no longer necessary 
[[microprofile-wg] [BALLOT] Replace MicroProfile Compatibility Logo with.pdf](https://github.com/microprofile/microprofile-wg/files/7551104/microprofile-wg.BALLOT.Replace.MicroProfile.Compatibility.Logo.with.pdf)
