### ISSUE TITLE
Marketing Plan & Budget

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#42]
from [git issue](https://github.com/eclipse/microprofile-marketing/issues/304)

[Drive](https://drive.google.com/drive/u/0/folders/1do4bZlfCcXqcPvhs3PquglX74eFUK-Ic)

**Comment by aeiras** [comment]
[Mktg Agenda April 5th call ](https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit#heading=h.woprq726kfgm)
[2021 MPWG Budget] ready to start review and shape 2021 Budget- Welcomes YOU to match the 2021 Program Plan! :)  (MP Community Thread) provides MicroProfilers the edit access, if you wish to work on the project plan, jump in. 

Relevant documents: the joining MicroProfiler is aware of the Project Plan Goals
2021 MPWG Project Plan
2021 Budget draft version .2 presentation
Drive budget documentation
Git issue

Working document: an excel sheet to allocate the money Inventory Costs Sheet

Surplus Budget Carry over 2020 Budget

After EF- EMO onboarding expenses, left over is: $1296

**Comment by TetianaFTV** [comment]
**Update based on the 5th of April call:** 

[Budget Document](https://docs.google.com/spreadsheets/d/1Xg0LbeQSH7MiJDmG_qm_BkcpK9Xacl2cE75fAzrEAOw/edit#gid=782165082)

**Approximate budget distribution:**

Total Marketing Budget | $37,000 | 100%
-- | -- | --
Swags & Events | $20,350 | 55%
Contingency | $3,700 | 10%
Infrastructure | $2,220 | 6%
Google AdWords | $5,550 | 15%
Paid social media, backlinks | $5,180 | 14%

**The next steps:**
- each member to review preliminary distribution and respond if there are any suggestions
- each member to check more detailed list in the [Budget Document](https://docs.google.com/spreadsheets/d/1Xg0LbeQSH7MiJDmG_qm_BkcpK9Xacl2cE75fAzrEAOw/edit#gid=782165082) (all the tabs) and leave comments or just edit the content if some activities should be added
- during the next MP Marketing Call (12.04) we'll discuss the final outcome and decide how to move on with more precise numbers per each option

**Comment by aeiras** [comment]
I adjusted the 1st tab under the budget summary to match the general distribution of the budget. Now, it matches. So fun!

**Comment by TetianaFTV** [comment]
@aeiras added the updated budget slide here
https://docs.google.com/presentation/d/1m2u3B79JWQ8R4dCx8WFtg7lIRpGTr1US/edit#slide=id.gd3076aa87a_0_3

**Comment by aeiras** [comment]
Completed via ballot vote [here](https://www.eclipse.org/lists/microprofile-wg/msg00902.html)
