### ISSUE TITLE
[Trademarks] MicroProfile Brand HandBook 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#45]
https://github.com/eclipse/microprofile-marketing/issues/404

[Drive](https://docs.google.com/document/d/1v7Chteluh4KrzLjFTCPLwvGccUpeKpcnQYzPiEjJQBU/edit)

**Comment by aeiras** [comment]
@rstjames, 

the word document contains the example from the Jakarta EE handbook. 
The MPWG doesn't have to be a replica to that document. 
We have completed and exported most of the MP work into the website already, lets use the document for a nice follow-up. 
Using google slides is ideal but any other format is also welcomed. Just keep everything in the Trademark drive that will provide public edit to anyone who wants to help. 

Next week fun work :) Let's do this!

**Comment by aeiras** [comment]
With @rstjames, we are going to start the work using the same format used as with Lars' MP White Paper. Doing so will welcomed feedback early and often while making it easier for Ryan to make great designs. :) Thanks Ryan for the thoughtful feedback and reminder to drop google slides. 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/10731224/115073513-4a6b2a00-9ead-11eb-90c2-45a2c537eb1a.png">

**Comment by aeiras** [comment]
@rstjames,

https://indd.adobe.com/view/c3d13bf2-e849-41ea-8c4e-bf47775826b7  bringing the crude draft on the book to this ticket.

**Comment by rstjames** [comment]
Here is the first draft of the MP branding manual. Please go to this link and leave your feedback. 
https://assets.adobe.com/id/urn:aaid:sc:US:52d9e7d5-c15b-4470-9837-923f42038dca?view=published

**Comment by rstjames** [comment]
Hi everyone. Here is the latest draft. Updated a couple of comments from people. Did not see many. https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:36dbb40b-eb90-49a7-80c6-1ca8074a0dc3

**Comment by aeiras** [comment]
@rstjames, 

The draft is a good start. I notice that it has not brought in components found in the Jakarta EE branding handbook. 
Can you please go into that document and notice what is missing from the draft. 

I have submitted a few comments but I have stopped until you have time to review the reference example added on the task.

**Comment by rstjames** [comment]
Version 2 is ready to review: 
https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:fa67622d-ca1f-48f2-bd13-5e5ac59efb94

**Comment by aeiras** [comment]
@rstjames fantastic improvements in version 2, thank you!
You added brightness and more detail to the handbook. 

I added further comments. I will create a word document where writing the history of the Mark is possible, that part is missing in the introduction of the book. Or if you want to own it, please go at it.  Happy to review your writing.

**Comment by rstjames** [comment]
latest updates for review: 
https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:dc9ffa1d-b03a-446f-9e1f-a24558b82057

**Comment by rstjames** [comment]
@aeiras I do not have time to write up the "history" of the logo. Let's push it out and we can add it later. I honestly couldn't tell you when I made the logo...  only that the community voted for it and there were a couple of other submissions.

**Comment by aeiras** [comment]
Ok, I will look into the community threads bc we used open brainstorming back when. 🥰

been almost 😅 5 yrs so totally ok to not remember stuff. Like you said, we can add it later if not found during this work period.

**Comment by aeiras** [comment]
I will review the latest version today.

**Comment by rstjames** [comment]
MicroProfile logo history:
In 201X the community came together and submitted a wide range of logo options that they felt could represent MicroProfile. When the submission deadline ended the community voted for which logo would represent MicroProfile. 

The winning logo was created by Ryan St. James (Tomitribe) 


@aeiras also what legal line do we need? (copywriter)

**Comment by aeiras** [comment]
The formal (legal) transfer from TT to EF on the MP logo took place on Sept 2017 @rstjames. 

Community thread: https://groups.google.com/g/microprofile/c/WtI2G1IWFC0/m/4370bcI_AgAJ

The logo has been in use formally since then in all MP content, swag, website, conference sessions, etc.

Logo submissions and selection took place in May & June 2017 via the community forum, many threads but will list 1 for [reference](https://groups.google.com/g/microprofile/c/QJY-LQp_KdY/m/-AysSHDYBgAJ)

This memory lane reminds me of the level of care and many of those conversations... it has been so long. :) 

-- your wording is great. Let's add the exact month of usage alongside the dates provided in the tracing and done. 

So much fun!

**Comment by rstjames** [comment]
Latest version: 
https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:c8481386-828c-4fd8-8a13-119355efd724

**Comment by aeiras** [comment]
Thank you, Ryan! 
Please expect my review on version 4 early next week. 

For history work and tracing, please drop the 3 versions in the [folder](https://drive.google.com/drive/u/0/folders/1zXwNllUjw3ftjsNdUVE7shmLe9UOuErc)

Abrazos,

**Comment by aeiras** [comment]
@rstjames, 

pretty an excellent version 4. I submitted what I believe are the final adjustments for v5. 
V5 will await the Compatible logo (1 slide) to be included as a mark, and then we can call the document final.  
Thank you for being very detailed in adding previews feedback in each version. It shows care!

Thank you for adding the 4 versions to the drive: https://drive.google.com/drive/u/0/folders/1zXwNllUjw3ftjsNdUVE7shmLe9UOuErc

**Comment by rstjames** [comment]
versions added to the drive and updated link 
https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:93178459-2bbd-44cd-bf30-eee3cf808715

**Comment by aeiras** [comment]
Ryan, 
I have no further comments on the document 💯 

Thank you for adding version 5 to the drive. 
I cannot save nor add version 1 through 4 to the drive. Can you please also add those versions?

Looking forward to the Compatible logo usage examples (from submitted logos) update you will show & tell on Monday. 
Ideally, you can use the tickets in advance to help with show and tell. Do pull me in via respective tickets if there is anything blocking you on that.

**Comment by aeiras** [comment]
Completed. It will be imported into the Website. 
It has been integrated into the MP Trademark Guidelines. 

@rstjames please see ticket 612. Thanks!

**Comment by SharonCorbett** [comment]
Please open a new Issue to request the Eclipse Foundation Marketing Team review and approve the Guidelines.  

This will need to be updated to the Eclipse Foundation artwork page in compliance with the Eclipse Foundation Trademark Policy upon the Eclipse Marketing Team's approval.

Regards,
Sharon

cc @paulbuck
