### ISSUE TITLE
[MP Product Plan] 2021 MicroProfile Program Plan Slide Deck - Russian Version

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#47]
https://github.com/eclipse/microprofile-marketing/issues/453

Fyi @mehmandarov :)

**Comment by mehmandarov** [comment]
Thanks, @aeiras. :) Feel free to assign this one to me and Mitia. I will have a look at it, but not before the next week.

**Comment by aeiras** [comment]
I don't have Mitia's git. :) Thats why, he should have open this ticket. lets send this ticket to the mktg forum and update him on it. You have nothing else to do but to enable Metia to own the ticket. :)

**Comment by mehmandarov** [comment]
I have now translated the document. Need to find someone to review my translation. Will send out an email.

Original Program Plan document:
https://docs.google.com/presentation/d/1-mu4dIsfAzLlE81splWBKwsGeRLJhzEWrXgsQ_i0JZQ/edit

Russian translation:
https://docs.google.com/presentation/d/1JnbIYsxyNtKcJ3kvkBg9cDpT41b2xy9F5Ag4NmZUvJM/edit

**Comment by mehmandarov** [comment]
@dalexandrov Can you review? :)

**Comment by TetianaFTV** [comment]
Made some editing of the texts. Rustam, hope I didn't messed up your surname :)
Anyway, considering that I'm not a native speaker, it would be good if Dmitry can make a final check.

**Comment by mehmandarov** [comment]
Thank you @TetianaFTV! I have reviewed the changes and made some minor revisions. I have also added a call for other reviewers through our [mailing list](https://groups.google.com/g/microprofile-marketing/c/uUgum2FdX7A), so we can give it another 2 weeks before we can close this issue and mark it as done - April 19th, 2021.

**Comment by mehmandarov** [comment]
TODO: We need to update the duke logo and watermarks.

**Comment by aeiras** [comment]
@mehmandarov, 

Are you ready to share it with the MP Community forum, Rustam?

Emerson is working on documenting the steps on translating... ideally, since you undertake this awesome task as well, you could help with that document that will become a wiki :) for translations. 
Once deadline is set, it ought to expand and include the entire community. 
Check Emerson's [Call to action](https://groups.google.com/g/microprofile/c/hCBSh-CdDnI/m/QK7ASK8IBAAJ)

**Comment by mehmandarov** [comment]
Yes, I am ready. :) Should I stick to English, or write it in Russian?

**Comment by aeiras** [comment]
Must be all in Russian of course! :)

**Comment by TetianaFTV** [comment]
@mehmandarov you can share Russian Plan version highlighting that you are the contributor of this Russian MP content with the card below:
![microprofile-cards-russian-contributor](https://user-images.githubusercontent.com/38689227/115723144-f5815500-a37f-11eb-92ef-70b05d9de35a.png)

**Comment by aeiras** [comment]
@TetianaFTV 
document is public https://docs.google.com/presentation/d/1JnbIYsxyNtKcJ3kvkBg9cDpT41b2xy9F5Ag4NmZUvJM/edit#slide=id.p

**Comment by TetianaFTV** [comment]
@aeiras please add here English version of the tweet for sharing the plan, so we can prepare Russian translation with the same message

**Comment by aeiras** [comment]
@TetianaFTV, 

A version is avaialble for review here https://github.com/microprofile/microprofile-wg/issues/72
with comment https://github.com/microprofile/microprofile-wg/issues/72#issuecomment-848977304

Leaving until Tuesday to collect feedback and then, you will have the Spanish version as well. thanks for the Russian version :)

**Comment by TetianaFTV** [comment]
possible Russian translation:

План программы @MicroProfile 2021 раскрывает основные стратегии и векторы в работе MicroProfile команды для достижения маркетинговых целей, роста сообщества, улучшения инфраструктуры и технологии, процесса спецификации и управления брендом совместимости

@mehmandarov please take a look and made any edits required

**Comment by mehmandarov** [comment]
Thank you, @TetianaFTV. I will do it tomorrow if it is ok for you. Please let me know if there is anything. 👍

**Comment by TetianaFTV** [comment]
Russian image (the original font doesn't support cyrillics, so we had to use another but similar looking)
![Program-Plan-2021_3](https://user-images.githubusercontent.com/38689227/121196615-ed6a6f80-c870-11eb-90f8-ab74c4df0f4e.png)

Tweet text: 
План программы @MicroProfileIO 2021 раскрывает основные стратегии и векторы в работе MicroProfile команды для достижения маркетинговых целей, роста сообщества, улучшения инфраструктуры и технологии, процесса спецификации и управления брендом совместимости

Full Link: https://drive.google.com/file/d/1NDqEZ6IC1njYRJOBErk9YkwAdj7ln1Ve/view
Short Link: https://bit.ly/3g0CuRG

@rstjames feel free to schedule it in Twitter

**Comment by aeiras** [comment]
@rstjames, 

The ticket is assigned to you. Thanks for the feedback! We missed the mark on these translation tickets at the end :)

Tetiana has created the image. We need your help with the Media schedule. 
Let's push it 1 per month up until Dec 31st, 2021.  Thanks, Ryan!

**Comment by rstjames** [comment]
ok but I am not the only one that can schedule on hootsuite or on tweetdeck. So no need to wait for me to schedule all these types of tasks.

Set to go out once a month for the rest of the year.

**Comment by aeiras** [comment]
> ok, but I am not the only one that can schedule on Hootsuite or on tweetdeck. So no need to wait for me to schedule all these types of tasks.
> 
> Set to go out once a month for the rest of the year.

Yes, currently, 3 of us can schedule stuff via MP media. 
I don't help with recurring—only the day of. 
Let's ask Tetiana via private Hootsuite if she knows how to help and if she wants to help. We cannot assume.  Tetiana is added to Hootsuite by her choice, which means she can contribute to schedule and planning. 

@rstjames, do you want to ask her on the next mktg call?
