### ISSUE TITLE
[Specification Process 1]: MicroProfile Platform release

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#48]
Reach a decision on status of MicroProfile platform
* Specification with TCK and compatible implementation
* Marketing-only document

**Comment by Emily-Jiang** [comment]
After some discussion, MicroProfile Platform release estabilished a process of claiming compatible implementation. Considering that it is impractical to require new runtimes that do not support Jakarta EE web profile to pass CDI, JAX-RS, JSON-B and JSON-P tcks. The agreement is: prior to the consumption of Jakarta Core profile, claiming on MicroProfile platform releases require passing the 8 MicroProfile specifications where passing the included Jakarta EE specs being optional. 
This decision will be revisited when MP consumes Jakarta Core Profile in due course.

From MP 4.1 and onwards, any runtime that passes the 8 included MP TCKs will be able to claim compliance.

**Comment by aeiras** [comment]
Hola Emily, 

Can you please share the community forum thread where this was discussed? Thank you,

**Comment by Emily-Jiang** [comment]
It was discussed on technical calls on 20th May https://docs.google.com/document/d/1Ou7mvxQdYjZJOkzvMmCAGvlYr04veQfvEyzW__CLrUU/edit#heading=h.o3w362ei7zzu. The decision was made to [MicroProfile spec doc](https://download.eclipse.org/microprofile/microprofile-4.1-RC2/microprofile-spec-4.1-RC2.html#required-apis) with the following statement:
"A MicroProfile compatible implementation must pass all required TCKs provided by each MicroProfile specification. Passing the MicroProfile optional TCKs is not required. Passing the Jakarta specifications TCKs is optional."
