### ISSUE TITLE
[informal- Media design template] MicroProfile Compatible Implementation Announcement Card Notification 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#51]
https://github.com/eclipse/microprofile-marketing/issues/455

Fyi @rstjames

**Comment by Emily-Jiang** [comment]
@aeiras remember to use the corresponding labels that @dblevins created.

**Comment by aeiras** [comment]
Hola Emily, 
David needs to create the labels, he volunteered:) 

I created Projects to complement the tickets. Hugs

**Comment by rstjames** [comment]
new visual. 
![microprofile-compatible_implementation](https://user-images.githubusercontent.com/12132146/112463474-96212c80-8d62-11eb-9b59-12535d919f13.png)

**Comment by aeiras** [comment]
@rstjames, 
Design looks great with the code. 
MicroProfile TM needs to convert to R. 
1 last try. 

Thank you,

**Comment by rstjames** [comment]
![microprofile-compatible_implementation](https://user-images.githubusercontent.com/12132146/112661769-29d42500-8e57-11eb-8b51-da32da0dce1b.png)

**Comment by aeiras** [comment]
Thank you, @rstjames. 
Closing ticket.  please drop it into the social media pushes to use later for informal media announcements when an implementation catches to  MP releases.
