### ISSUE TITLE
[MPWG Page] Add MPWG Repo link under Knowledge Section

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#53]
**Description:** 

[MPWG Repository](https://github.com/microprofile/microprofile-wg/issues) is used for all activities including the MPWG releases, the execution of the Yearly Project Plan & more.

**Comment by rstjames** [comment]
Updated.

**Comment by aeiras** [comment]
amazing. Added to the agenda already. Tetiana already set-up the agenda. 
Please Ryan, do make sure you add closed tickets there as well. It is easy for me to miss stuff. :)
