### ISSUE TITLE
MicroProfile Fault Tolerance 3.0 Specification Review

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-wg#6]
**Specification issue template**

When creating a specification project release review, create an issue in the [MicroProfile-WG repository](https://github.com/microprofile/microprofile-wg) repo with the content defined as follows.
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNN where NNN is the staging repository id) (eg, https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-spec/3.0/microprofile-fault-tolerance-spec-3.0.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-spec/3.0/microprofile-fault-tolerance-spec-3.0.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-api/3.0/microprofile-fault-tolerance-api-3.0-javadoc.jar)
   - [x] [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-api/3.0/microprofile-fault-tolerance-api-3.0.jar)
   - [x] [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1400/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-tck/3.0/microprofile-fault-tolerance-tck-3.0.jar)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-fault-tolerance-3.0/
   - [x] An [apidocs](https://download.eclipse.org/microprofile/staging/microprofile-fault-tolerance-3.0/apidocs/) directory containing the javadoc associated with the API jar.
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request] (https://github.com/eclipse/microprofile-fault-tolerance/issues/586)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/reviews/fault-tolerance-3.0-release-review)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569635) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by Emily-Jiang** [comment]
@aeiras will you be able to intitiate the ballot by sending an email to microprofile-wg detailed in this issue?

**Comment by radcortez** [comment]
+1

**Comment by dblevins** [comment]
Vote started!  Note we should only put "ballot" on the issue once it's up for vote.  I added a new label "ready for ballot" to indicate that action by the mentor is needed.

**Comment by aeiras** [comment]
we can do it!!!

**Comment by emecas** [comment]
+1

**Comment by kwsutter** [comment]
The Component Release Record should be pointing at https://projects.eclipse.org/projects/technology.microprofile/reviews/fault-tolerance-3.0-release-review

The staged apidocs directory (https://download.eclipse.org/microprofile/staging/microprofile-fault-tolerance-3.0/apidocs/) is malformed.  The javadoc jar looks fine, so this is a nit.  But, it should get cleaned up.

And, a couple of comments on the [CCR](https://github.com/eclipse/microprofile-fault-tolerance/issues/586) (just like the other CCRs I've been reviewing).

Nothing to prevent my +1, but these items should be cleaned up before going final.

**Comment by radcortez** [comment]
Updated.

**Comment by kwsutter** [comment]
> Updated.

Thanks, @radcortez.  The staged apidocs is still malformed, but the other items were updated, including the CCR.  Thanks!

**Comment by Emily-Jiang** [comment]
> > Updated.
> 
> Thanks, @radcortez. The staged apidocs is still malformed, but the other items were updated, including the CCR. Thanks!

@kwsutter the apidocs link works fine for me. Which browser are you using?

**Comment by kwsutter** [comment]
> > > Updated.
> > 
> > 
> > Thanks, @radcortez. The staged apidocs is still malformed, but the other items were updated, including the CCR. Thanks!
> 
> @kwsutter the apidocs link works fine for me. Which browser are you using?

Yeah, @radcortez and I figured out it must be something with Firefox.  When I tried Chrome, everything was just fine.  But, my Firefox doesn't present the javadoc correctly...  Not a big deal.

**Comment by Emily-Jiang** [comment]
@dblevins I think we can close the ballot now as all 5 memembers cast their votes and 7 days have elapsed. Will you be able to do the final announcement? Thanks!
