### ISSUE TITLE
Define "MicroProfile Compatibility"

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-wg#64]
From the "additional goals" category of the program plan, but ties into other goals as well.

**Comment by aeiras** [comment]
decided with
[[microprofile-wg] [BALLOT] Replace MicroProfile Compatibility Logo with.pdf](https://github.com/microprofile/microprofile-wg/files/7551097/microprofile-wg.BALLOT.Replace.MicroProfile.Compatibility.Logo.with.pdf)
