### ISSUE TITLE
Awareness of the Spanish Plan version via MP Twitter

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-wg#72]
### Tweet Text:

El Plan Anual MicroProfile 2021 disponible en Español: https://drive.google.com/file/d/1_zLvW57P6sKMknI5fHFj0lyPD4qRoIwT/view?usp=sharing incluye Objetivos Estratégicos, Técnicos, y para Extensión de la Comunidad, Actividades de Marketing, Proceso de Especificación, Compatibilidad y Marca

This relates to:
https://github.com/eclipse/microprofile-marketing/issues/399
https://github.com/microprofile/microprofile-wg/issues/44

**Comment by aeiras** [comment]
@rstjames, 

can you please help us shorter the link above?

@emecas, so fantastic.  I am happy to run a final review in twitter once we have the link from Ryan. 

Ryan, do you think we could run this media push 1 per month or what timeline do you recommend. It goes from April to Dec 31st to match the year? 
The goal is to bring awareness of the work being done and hopefully increase onboarding MicroProfile from Spanish speaking countries. 

With that in mind, the same will happen with Russia translation which is being worked on this week!  :)

**Comment by TetianaFTV** [comment]
@emecas you can share Spanish Plan version highlighting that you are the contributor of this Spanish MP content with the card below:

![microprofile-cards-spanish-contributor](https://user-images.githubusercontent.com/38689227/115722956-c66ae380-a37f-11eb-8ab5-f8a4563acbbc.png)

**Comment by aeiras** [comment]
@emecas, 
Thank you for creating this ticket that enables the brainstorming for the message to share the 3 documents. 

Using your draft:

_The MicroProfile 2021 Project Plan lists the MicroProfilers' strategic trajectory of their work on marketing activities, growth with the community, infrastructure, technical objectives, specification process & compatibility brand management. [LINK]

#ByCommunityForCommunity_

**Things to note**:

1. removed the language b/c the write up makes the language clear enough and also efficient! :) 
2. included the people doing the work, MicroProfilers
2. using the presentation, the order of the tasks is listed
3. added hashtag

What else is missing? There will be only 1 message translated into thus far, Spanish & Russian. 
Thanks for looking into this.

**Comment by aeiras** [comment]
@TetianaFTV if you could check the suggested English version for grammatical errors and impact on the message that would be great! thanks

**Comment by TetianaFTV** [comment]
**some edits as the version above is a bit too long if we add the link:**

The @MicroProfile 2021 Project Plan lists the strategic trajectory of MicroProfilers' work on marketing, community growth, infrastructure enhancements, technical objectives, specification process & compatibility brand management

#ByCommunityForCommunity

**Comment by aeiras** [comment]
reads good, Tetiana!

@rstjames can you please help us create a special short-link for the Program Plan in English? Thank you! 
1 link houses 3 translations: 

- [ 2021](https://drive.google.com/drive/folders/11RQe2ONXqqK4YQUfXtvNtMJYq_IfEiji)

For design I recommend:

- 2021 large using the title of each Translation
- #ByCommunityForCommunity
- Open Souce

@emecas can you  please help translate to Spanish the version's revised on this thread? I can review to make it final for media push :) 

@TetianaFTV do you wish to help create the design that will be adjusted for the 3 different translations? Or do you prefer that Ryan takes that task? 

Lets do this,

**Comment by TetianaFTV** [comment]
here is the design for the tweet

![Program-Plan-2021](https://user-images.githubusercontent.com/38689227/120455215-d9b49a00-c394-11eb-860c-d1727908276d.png)

if it's ok we can later make Russian and Spanish versions

**Comment by aeiras** [comment]
@TetianaFTV, 

Thank you for getting stuff forward. Feedback as follows:

- [ ] I like the people in the room collaborating! 

- [ ] It is hard to read the focus-listed items in the plan.  how about their re-distrubition as done with the Charter template? 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/10731224/120511656-73714c80-c37f-11eb-90cb-9c3adc280992.png">
 twitter[ link](https://twitter.com/MicroProfileIO/status/1399750837304442887?s=20)

**Comment by aeiras** [comment]
the template is in the drive, you could use that template to include a background image and change the borders and done.

**Comment by emecas** [comment]
> @emecas can you please help translate to Spanish the version's revised on this thread? I can review to make it final for media push :)

Sure, want about this? @aeiras 

**English Version:**

_The MicroProfile 2021 Project Plan lists the MicroProfilers' strategic trajectory of their work on marketing activities, growth with the community, infrastructure, technical objectives, specification process & compatibility brand management. [LINK]

#ByCommunityForCommunity_

**Spanish Version**

_El Plan Anual MicroProfile 2021 incluye las estrategias de trabajo para los MicroProfilers dentro de las actividades de marketing, extensión de la comunidad, infraestructura, objetivos técnicos, proceso de especificación y  programa de marca y compatibilidad. [LINK] 

#ByCommunityForCommunity_

**Comment by aeiras** [comment]
there is only change recommended.  How about replacing the "extension de la Comunidad" con **bienestar y crecimiento de la comunidad**. 

**Spanish Version**

_El Plan Anual MicroProfile 2021 incluye las estrategias de trabajo para los MicroProfilers dentro de las actividades de marketing, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación y programa de marca y compatibilidad. [LINK]

#ByCommunityForCommunity_

**Comment by aeiras** [comment]
@TetianaFTV, it is a go from me. :)

Can you also help with the design in Spanish
**Spanish Version**

_El Plan Anual MicroProfile 2021 incluye las estrategias de trabajo para los MicroProfilers dentro de las actividades de mercadeo, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación y programa de marca y compatibilidad. [add the LINK- shortern customized URL in **spanish/Rusian/English respectively**. ]   

#ByCommunityForCommunity_

**Comment by TetianaFTV** [comment]
@aeiras please provide Spanish translation for the texts on the image, so I can prepare its Spanish version

**Comment by aeiras** [comment]
Here you go and thanks Tetiana!

**Title**
Plan Anual MicroProfile 2021
 **tasks:** 
mercadeo, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación y programa de marca y compatibilidad

**Comment by TetianaFTV** [comment]
@aeiras why don't we have a Spanish version of the presentation in the folder with others?
https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C
I know for sure that it was uploaded there but now I don't see it

**Comment by TetianaFTV** [comment]
Spanish image

![Program-Plan-2021_2](https://user-images.githubusercontent.com/38689227/121195392-d8411100-c86f-11eb-8146-7de6c31684a0.png)

the twitter text is too long if pasting together with the link, so I shortened it a bit:

**Plan Anual MicroProfile 2021 incluye las estrategias para los MicroProfilers dentro de las actividades de mercadeo, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación, programa de marca y compatibilidad**

@aeiras please check if it's ok from Spanish point of view
Also, we need to figure out where is the final version of the Spanish presentation and upload it again to the [folder](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C) for Ryan to be able to use a proper link while scheduling the tweet

**Comment by aeiras** [comment]
The text reads great, @TetianaFTV! 

https://drive.google.com/drive/u/0/folders/1Cfhh3v799Tb_lTrBOIrm3dninpM9pCCt  under the Community Working Group_restrictive folder you can find the finalized documents. 
We need the word documents to stay in the Community folder. PDF "finalized' always ok in the formal MPWG drive. 
I added the word version to the folder. Ideally you PDF as you have done with the other documents. 
Yet note that when we use PDF, the contributors, and notes within the document are lost. 

I recommend we drop PDF and use the word versions of each document better. 
That is what we do for the Prospectus.

**Comment by aeiras** [comment]
> Spanish image
> 
> ![Program-Plan-2021_2](https://user-images.githubusercontent.com/38689227/121195392-d8411100-c86f-11eb-8146-7de6c31684a0.png)
> 
> the twitter text is too long if pasting together with the link, so I shortened it a bit:
> 
> **Plan Anual MicroProfile 2021 incluye las estrategias para los MicroProfilers dentro de las actividades de mercadeo, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación, programa de marca y compatibilidad**
> 
> @aeiras please check if it's ok from Spanish point of view
> Also, we need to figure out where is the final version of the Spanish presentation and upload it again to the [folder](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C) for Ryan to be able to use a proper link while scheduling the tweet

@rstjames, 

Same as the other ticket about the Russian message.  1 per month. And Prospectus goes until the end of the year as well. Gracias! :)

**Comment by rstjames** [comment]
@aeiras @TetianaFTV 
- Can someone confirm these are the final messages? 
- Can we make it a habit at the end of a very long thread we recap the "final" agreed content? That way there are no mistakes. 
- Please let me know when we have final LINKS for these tweets

**English Version:**
The MicroProfile 2021 Project Plan lists the MicroProfilers' strategic trajectory of their work on marketing activities, growth with the community, infrastructure, technical objectives, specification process & compatibility brand management. [LINK]

#ByCommunityForCommunity

![120642268-f88a5d80-c474-11eb-861b-84b6c122fc88](https://user-images.githubusercontent.com/12132146/122747833-ce65d780-d28b-11eb-90ba-abb444abfcfd.png)


**Spanish Version**
Plan Anual MicroProfile 2021 incluye las estrategias para los MicroProfilers dentro de las actividades de mercadeo, bienestar y crecimiento de la comunidad, infraestructura, objetivos técnicos, proceso de especificación, programa de marca y compatibilidad [LINK]

#ByCommunityForCommunity

 
![121195392-d8411100-c86f-11eb-8146-7de6c31684a0](https://user-images.githubusercontent.com/12132146/122747880-dc1b5d00-d28b-11eb-8686-5788309e1b27.png)

**Comment by rstjames** [comment]
each are set to go out once a month for the year
