### ISSUE TITLE
Prospectus document - Spanish Version

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-wg#73]
Help on the translation of the [Prospectus Document ](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.g6edf059ff0_56_0)  Spanish Version 

English Version: https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.g6edf059ff0_56_0

**Comment by emecas** [comment]
A First Draft [WIP - 50% done]: https://docs.google.com/presentation/d/1B1uRPNAox5iSL2pOsaI_1ogmjR9MBcmUDb79u-fyHzA/edit#slide=id.g77280c392b_2_6

**Comment by aeiras** [comment]
wow, i will be happy to contribute on review once you complete the translation Emerson. 
Remember to add the task to the Mktg agenda for next Mktg call should you have completed the translation and do the same thing we did for the Program document. Iterate. This time, I won't help you with logistics. 

Ideally, you are motivated to write the Spanish guidelines on how to own the work you are currently doing. The steps.  You see, only you are equipped to document how important truly is what you are doing. The document will be become a wiki on this Repo via a PR that you will submit. That is if you are able to document and provide example on how you got stuff done, git issues used, threads sent, etc. 

Keep your awesomeness,

**Comment by emecas** [comment]
Final draft is completed  and ready for review https://docs.google.com/presentation/d/1B1uRPNAox5iSL2pOsaI_1ogmjR9MBcmUDb79u-fyHzA/edit#slide=id.g77280c392b_2_6


I was going to add the task to the marketing agenda ,but it is already there, but  for Apr 12 meeting, since Apr 5 is just for budget discussion, meanwhile I am going to start thinking how to approach the wiki idea you have mentioned before.

**Comment by mehmandarov** [comment]
Great, @emecas! Thank you!

**Comment by aeiras** [comment]
@emecas do follow suit by sending call to action to review to the community forum. You could set up a 2 or 3 weeks' window, up to you to provide the deadline. minimum 2 weeks. :) you can be as nice as you want with extra week!

**Comment by emecas** [comment]
> 
> 
> @emecas do follow suit by sending call to action to review to the community forum. You could set up a 2 or 3 weeks' window, up to you to provide the deadline. minimum 2 weeks. :) you can be as nice as you want with extra week!

Done,  Community forum conversation: https://groups.google.com/g/microprofile/c/97yxkCWRdOI

**Comment by mehmandarov** [comment]
@emecas: Just beware of the same link permissions problem here as well. The link in the email seems to be broken. :)

**Comment by emecas** [comment]
> 
> 
> @emecas: Just beware of the same link permissions problem here as well. The link in the email seems to be broken. :)

thanks @mehmandarov  it should be fixed now, please let me know if it is not the case

**Comment by mehmandarov** [comment]
Not the link from the email you have linked here: https://groups.google.com/g/microprofile/c/97yxkCWRdOI. I have tried with two different accounts. Both say "You need access". :-/

**Comment by emecas** [comment]
> 
> 
> Not the link from the email you have linked here: https://groups.google.com/g/microprofile/c/97yxkCWRdOI. I have tried with two different accounts. Both say "You need access". :-/

you are right , the one at the bottom of the email is not working and I could not fix it. May you please try this link, the one in the email's body : https://docs.google.com/presentation/d/1B1uRPNAox5iSL2pOsaI_1ogmjR9MBcmUDb79u-fyHzA/edit

**Comment by mehmandarov** [comment]
You are right, @emecas! It works! Thanks! 🎉

**Comment by aeiras** [comment]
@emecas, 

I cannot start the review because the document is not hosted under the MP Community folder. 
Remember that when collaborating in anything MP related to Marketing, the usage of INFRA tools recognized as formal for collaboration are required. 

Cheers

**Comment by emecas** [comment]
@aeiras 

I tried to move it to `MicroProfile Drive` ->  `Working Group` -> `Prospectus` folder, but it did not let me do it, so I ended  moving it to  `MicroProfile Drive` -> `Community` -> `Working Group` folder

No idea if this is because an access problem or if there are other " INFRA tools recognized as formal for collaboration" ?

**Comment by aeiras** [comment]
omgosh, you were also affected by the google bug (~2 weeks ago). Please check again. 
I reviewed each folder of MP last week and everything should be back to normal. 
Apologies, I forgot to send a msg to the mktg forum after completing that review. 

Pull me via this ticket for anything related to issues with the drive and this task. Deadline is here : )Lets do this!

**Comment by emecas** [comment]
thank you @aeiras  and sure let's try to fix driver issues here.

I'm sorry if i am going over the same topic again, but I'm asking because I'm not 100% sure what "back to normal" means :) , mainly because my access (in genera before and now) has been pretty restricted, so at least for now please let me so where do yo want this document to live so I can review if i can place it on that particular location  

As I mentioned before I moved it to `MicroProfile Drive` -> `Community` -> `Working Group` Folder. Is that the right place? 

Also asking because I've tried to see where the original is located, but it's just showing me this: 

![image](https://user-images.githubusercontent.com/849502/115311740-c5df0c80-a135-11eb-81d2-52779fbba3cc.png)

**Comment by aeiras** [comment]
You are not wrong Emerson in asking questions. 
Under the MP Community drive, there are only a few folders that welcome anyone, anywhere to have full edit access to the content. For example full edit access:

- Community folders
- Minutes folder
- Blog/content creation

The other folders are "view" only and have always been restricted to have "view". The MP Admin access provides a list of people with full access across the MP tools, not only Drive. 

Correct about dropping the translation into the Community >MPWG. 
The original document for the Prospectus is under "view only" and you won't be able to move the document but actually make a PDF copy and drop it into the Community folder-- working logistics. 

Such "view" restrictions allow finalized documents to be protected. In google drive we cannot track what Admins do, so we limit exposure & are deeply careful about how stuff gets moved & why. There is usually tracking via git tickets to welcome others' to help organize stuff. : )
When I say back to "normal" is b/c the Community folder was adjusted to restrict anyone from editing stuff, which is wrong. Now fixed. 

I hope this follow up is helpful. Questions, shoot. We don't even have a wiki for the google drive navigation. Maybe you want to own that based on what you are learning after Prospectus is done? : )  Like that, others like you don't have to wonder about stuff.

**Comment by aeiras** [comment]
Hola @emecas, 

Can you add your name to the first page of the document as you did for the Program?  Credit is due. 
I added our names to the comments section as well. 

I will review the document carefully once again next week. before we convert it to PDF. Great job Latin Armada!

**Comment by LuisGalazM** [comment]
Hola,
I wrote some suggestions as comments in the document.
Saludos!

**Comment by aeiras** [comment]
Que chevere, Luis! 
let us work with you on the feedback early next week 💪🏼🥋 thanks for your time & help 💛

**Comment by aeiras** [comment]
@LuisGalazM thank you for using red to add the word, easy to catch and appropriate. Note that your name was added on 2nd page as a Contributor.  Your input is accepted. 

@emecas, 
I have reviewed the document once again, I used "red" to add stuff, emulating Luis's feedback :) 
Also adjust stuff, deleted stuff.  The quotes are complicated but doable. 

In short, this project translation allows us to see that the current Prospectus will be edited a bit later this year. There are parts that are too repetitive in it. I wrote it with John yet only during this collaboration I am noticing the extra wording. 

Thank you for leading this effort. Please check the stuff and let us know when to return to the review before finalizing it.

**Comment by LuisGalazM** [comment]
@aeiras la verdad es que yo utilize comentarios, que @emecas resolvio ayer. Las palabras en rojo ya estaban ahi :).

**Comment by aeiras** [comment]
Luis, I saw a message from you but it is no longer here. 
Super chevere tenerte aqui ayudando con la traduction. 
Google slides doesn't allow us to track changes, the only way is to look into the history which is very time consuming. 

Abrazos,

**Comment by emecas** [comment]
@aeiras as @LuisGalazM  mentioned I was the one who left some words in red, because I had not a decided translation, but from all suggestions/comments that was completed, accepted all Luis's suggestions in the document, leaving in pending only the cite for IBM , @LuisGalazM  thank you so much for your observations

@aeiras I noticed you added multiple suggestions in red, are those the definitive wording? if that is the case I will accept them today or I will give some feedback for a couple of them.  Also It is weird that suggestion mode does not work for you as it worked for Luis.

**Comment by aeiras** [comment]
Yes, the red is suggested wording, Emerson. 
Sadly, I was not able to get the "suggested mode" to work for me so when I deleted stuff you won't see as easy, yawn. 

Thank you for looking into it, Latino!

**Comment by emecas** [comment]
> 
> 
> Yes, the red is suggested wording, Emerson.
> Sadly, I was not able to get the "suggested mode" to work for me so when I deleted stuff you won't see as easy, yawn.
> 
> Thank you for looking into it, Latino!

DONE , I added a comment for the only suggestion from you @aeiras that I did not accept, suggesting an alternative translation.

Thanks

**Comment by emecas** [comment]
I have applied the last update that was in pending, the IBM's cite text, it is now according to the original [missed] text as well as I had to extend the shape and text-field in order to make the new text'd fits visually

@aeiras@tomitribe.com and @LuisGalazM any additional feedback is welcome

**Comment by emecas** [comment]
Thanks @aeiras , as advised same as we did in #44  I have made that last change, final version is ready!!!

**Comment by aeiras** [comment]
Emerson and Luis, 

The document is now on its way to being published via all MP areas:  

- ticket 512 helps MP media publish the document as often as the English version. 

- ticket 511 adds the Prospectus to the MPWG website

Emerson, 

1. I adjusted a few more things with colors that we overlooked before
2. the document stays in word version, never PDF
3. it is moved to the MPWG >Prospect folder, and Public edit is restricted (showing finalized version)

**Todo**

- Emerson, you could and ought to be the first to share the document via Twitter and, in your own words, share why you chose to translate it. Why do you care?  - Tweet your thoughts in Spanish, of course.  Like that the MP handle can re-tweet you. Your healthy noise matters, protect your collaboration, and let the media of MP highlight you with re-tweets. 
**You are welcomed to** 
- to revise the 2 tickets I created. If there is anything that can be improved, provide feedback on the tickets. 
- close this ticket :) 

Formidable work, Emerson! 
Thank you Luis for choosing to contribute, you are listed on the 2nd page as well! If you provide your twitter handle, we could add you there, if you don't have twitter, you could use your GitHub ID or whatever personal media contact you prefer. Do let us know.

**Comment by LuisGalazM** [comment]
@aeiras, I'm glad I was able to help. My twitter handle is @GalazOnline

**Comment by aeiras** [comment]
Luis, 
Your Twitter profile has been added on the 1st page of the document, gracias! 

The Prospectus is now added side by side https://microprofile.io/workinggroup/ on the MPWG page 
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/10731224/120384283-cfce6080-c2da-11eb-9564-aa5d5a5cfe3e.png">
as indicated in the other git ticket. 

the social media ticket is pending as the last item. 

@emecas and @LuisGalazM, 
thank you for continuing to show up and via actions own the work that matches the talk!

**Comment by aeiras** [comment]
@emecas please add stuff to the Mktg agenda on this under "completed work", congratulations to YOU!

**Comment by emecas** [comment]
Thanks @aeiras , The link in the web site "Aprende Mas" is not accessible to the public same as "Learn More"

**Comment by aeiras** [comment]
Fixed. 
Gracias, Emerson! :)
