### ISSUE TITLE
[MP Compatibility Logo Submission] Versions from Jelastic

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-wg#78]
Here are some versions of MP compatibility logo from Jelastic team:

**Version 1**
- dark background https://drive.google.com/file/d/1wQ5vFUWk8DYKgEcTPsNDWa8-VG2eIwIY/view

- white background https://drive.google.com/file/d/1FSd4bK78FVNeqzxKSTBWH-89K7S3P4Tc/view

![microprofile-compatible-v1-jelastic](https://user-images.githubusercontent.com/38689227/115607882-d209cc00-a2e5-11eb-8146-3fef2a671537.png)

![microprofile-compatible-v1-white-jelastic](https://user-images.githubusercontent.com/38689227/115607913-dd5cf780-a2e5-11eb-82cd-d72171a25d54.png)

**Version 2**
https://drive.google.com/file/d/1blzon_bOuaQX0mSCSntLwqJKIIgif5s1/view

![microprofile-compatible-v2-jelastic](https://user-images.githubusercontent.com/38689227/115607932-e352d880-a2e5-11eb-808f-b3ce1c17db49.png)

**Comment by aeiras** [comment]
@TetianaFTV this is the area where feedback will be provided to the work submitted. Ticket needs to remind open until the winning logo is out.

**Comment by rstjames** [comment]
@TetianaFTV can view the layout for voting here https://drive.google.com/drive/u/1/folders/1unMeyPjVudkheFUKnpWYahAtAkT6An0b

**Comment by TetianaFTV** [comment]
looks good, thanks!

**Comment by aeiras** [comment]
MP can choose a TCK compatible logo based on the submissions but not as part of the trademark program.
[[microprofile-wg] [BALLOT] Replace MicroProfile Compatibility Logo with.pdf](https://github.com/microprofile/microprofile-wg/files/7551150/microprofile-wg.BALLOT.Replace.MicroProfile.Compatibility.Logo.with.pdf)
