### ISSUE TITLE
[MP Licenses]   Implementation vs Compatible Patent comparison - Document

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-wg#79]
In order to start this particular task, that came out during our yesterday [meeting - April 27](https://docs.google.com/document/d/1haN2ru2e1flrZ2w07e5Mh3WpMs2713ixz5Ue7hs4uAg/edit) a quick follow up here. 

If I am not bad I heard you said @aeiras  we have 48 hours for the subject, so I am wondering how we must start the conversation / work about patent licenses document elaboration.

Is there an equivalent work/template we could use as a base?

In addition to the [tweet](https://twitter.com/MicroProfileIO/status/1387109608678825984?s=20) :

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Happening now +23 <a href="https://twitter.com/hashtag/MicroProfilers?src=hash&amp;ref_src=twsrc%5Etfw">#MicroProfilers</a> 💛 are part of the discussion with the <a href="https://twitter.com/EclipseFdn?ref_src=twsrc%5Etfw">@EclipseFdn</a> EMO Team on Patent Licenses in the Context of the <a href="https://twitter.com/hashtag/EFSP?src=hash&amp;ref_src=twsrc%5Etfw">#EFSP</a>. Disclaimer: This call is NOT recorded. <br><br>Join <a href="https://twitter.com/hashtag/opensource?src=hash&amp;ref_src=twsrc%5Etfw">#opensource</a> <a href="https://t.co/VorMTALLIa">https://t.co/VorMTALLIa</a> <a href="https://t.co/oYjAcwsog1">pic.twitter.com/oYjAcwsog1</a></p>&mdash; MicroProfile (@MicroProfileIO) <a href="https://twitter.com/MicroProfileIO/status/1387109608678825984?ref_src=twsrc%5Etfw">April 27, 2021</a></blockquote>

These are the only  3 start points / references I was able to save yesterday:

[1] INTELLECTUAL PROPERTY POLICY
https://www.eclipse.org/org/documents/Eclipse_IP_Policy.pdf

[2] Eclipse Foundation Specification License – v1.0
https://www.eclipse.org/legal/efsl.php

[3] Slide
![image](https://user-images.githubusercontent.com/849502/116446439-935f9e80-a81c-11eb-8aa3-c12df6edf9dc.png)

**Comment by aeiras** [comment]
Thank you, @emecas!

[Implementation vs. Compatible Comprehensive Analysis
](https://docs.google.com/document/d/1kZQ1jB632jb0fZz1_PuHN7-QRwP4E2CAd59XTBRTCcY/edit#) is ready to absorb the facts on the 2 choices to enable effective conversation. 

You are most welcomed to start populating the pros and cons under each choice, if you have the bandwith to use the document provided during yesterday call. Ideally, we are done with the "draft" write it by the end of our day tomorrow.

**Comment by aeiras** [comment]
I will get to the document latest tmw AM.

**Comment by aeiras** [comment]
With legal, I won’t connect until next week. The 48hrs as I imagine is too aggressive. 

That’s why there is no accepted “deadline” on this topic to rush to a badly understanding of the 2 choices. 

Emerson, you are most welcomed to do research & add stuff as you see fit during these time. 

Abrazos,

**Comment by aeiras** [comment]
@emecas, 

Thank you for wishing to help. 
Based on much of the feedback due to "legal" concerns, The legal document couldn't be created. 
 Instead, the informal, factual via example sharing of the patents has been sent, enabling the creation of the wiki.

 Wiki https://github.com/microprofile/microprofile-wg/wiki/Patent-Example-with-LRA

Closing this ticket!
