### ISSUE TITLE
[MP Compatibility Logo Submission] Versions from Emerson

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-wg#80]
Following the [guidelines ](https://docs.google.com/document/d/1pcEducp-lEC0o0I3hRRzt3Kc-uC-hN3zQ-Yj1MqSuiE/edit#) for participation and submitting a logo, here are some versions of MP Compatibility Logo from myself:

#ByCommunityForCommunity

### Full Color Version(s)
link: https://drive.google.com/file/d/1mEjIeMohH_UbH3zDOdAlfOcKAcQcRe7o/view?usp=sharing
![image](https://user-images.githubusercontent.com/849502/116492127-17d41080-a861-11eb-896f-12ae92ff678e.png)

### My Full Color Version Favorite One
link: https://drive.google.com/file/d/1wtZVm2exuiUKPfCZilx0uZpNFRbJHc54/view?usp=sharing
![image](https://user-images.githubusercontent.com/849502/116492727-9e3d2200-a862-11eb-8d9c-d72659fdfb1f.png)

### One Color Version
link: https://drive.google.com/file/d/1V2Jp7RcdFXnR53axK15Iy2Y74fd6dYu4/view?usp=sharing
![image](https://user-images.githubusercontent.com/849502/116492177-3df9b080-a861-11eb-96b1-6fdeba2c8ad9.png)

_**Disclaimer**: this is not my area of expertise , but I felt like contributing with some logos :)_

**Comment by rstjames** [comment]
@emecas could you please make a version where the sticky note and the logo are not angled?  Part of the "branding guidelines" that are being put together right now. Please let me know if you have any questions. Thank you.

**Comment by emecas** [comment]
Sure!!! here you go, I have added those to the folder as well , thanks @rstjames

![image](https://user-images.githubusercontent.com/849502/117867822-7be1d600-b25e-11eb-9db5-d0897f04d551.png)

![image](https://user-images.githubusercontent.com/849502/117867850-81d7b700-b25e-11eb-9fde-f437e1275914.png)

**Comment by rstjames** [comment]
@emecas thanks bud

**Comment by rstjames** [comment]
@emecas you can view the voting template here for each logo https://drive.google.com/drive/u/1/folders/1unMeyPjVudkheFUKnpWYahAtAkT6An0b

**Comment by emecas** [comment]
thank you @rstjames , since versions submitted were just PNG files exports ( no taking  much care about scale),  I'm wondering if i can provide logos with better resolution for each of the required sizes you are presenting in the template ? If that is the case , do you have the different resolutions in the template ?

**Comment by rstjames** [comment]
@emecas sure send me better quality if you have it and is there a way to make a ONE color (white) no shading,  no background like the other examples? This one color is needed for scalability and if it will ever be printed (with limted color print- example shirts)

**Comment by Emily-Jiang** [comment]
@emecas thanks for the design! Looks good! One comment: I am not sure about the pin as it is used for sticky notes - pretty much temp things. I am wondering whether you think it can be removed. If you disagree, it is fine too, as this is my personal feedback. @aeiras please feel free to comment further based on our conversation during the call today.

**Comment by aeiras** [comment]
Lunes @emecas, 

I wonder how attached are you to the pin? 
I recommend its removal; however, it is for the time being still your design.  You can adjust it and protect it as much as you wish. 

Thanks, Emily for the prompt reminder after today's focused call. You rock!

**Comment by emecas** [comment]
thanks @Emily-Jiang and @aeiras ,  I think removing the pin is a good idea, actually the pin is giving me issues to get the asked version one color (white) no shading. I will give a try!!!

**Comment by aeiras** [comment]
Emerson, always do what you think is best, regardless of feedback. 
Bounce back any further ideas you might have. You got us, we gotU! :)

**Comment by rstjames** [comment]
@emecas hey bud. we need an update on this sooner than later. thanks

**Comment by emecas** [comment]
Thank you for your feedback @rstjames  @Emily-Jiang @aeiras , 

**Color**
![image](https://user-images.githubusercontent.com/849502/125002459-f9d61980-e022-11eb-9dbd-7679228614e7.png)

**One color (white) no shading, no background**
![image](https://user-images.githubusercontent.com/849502/125002492-0ce8e980-e023-11eb-9202-852b5fae6af7.png)

**Comment by rstjames** [comment]
@emecas Sorry for the very late reply. I think I explained it wrong. We need a logo that is ONE color so white and blue ( "blue"could be any color) is just a background. We need this one color logo with no gradients or dots (paper curl) because if this logo was chosen it needs to be able to be printed on t-shirts which normally is a one color print. 

This is an example of what I am referring to for your logo: These fit the requirements. 

Which one would you prefer? 

<img width="493" alt="Screen Shot 2021-08-09 at 8 16 50 PM" src="https://user-images.githubusercontent.com/12132146/128754505-a688da28-48e5-4ea0-957b-d18279d11bf6.png">

**Comment by emecas** [comment]
> 
> 
> @emecas Sorry for the very late reply. I think I explained it wrong. We need a logo that is ONE color so white and blue ( "blue"could be any color) is just a background. We need this one color logo with no gradients or dots (paper curl) because if this logo was chosen it needs to be able to be printed on t-shirts which normally is a one color print.
> 
> This is an example of what I am referring to for your logo: These fit the requirements.
> 
> Which one would you prefer?
> <img alt="Screen Shot 2021-08-09 at 8 21 06 PM" width="445" src="https://user-images.githubusercontent.com/12132146/128754804-7481042a-d45b-4334-ba08-d4609149fee3.png">

Thanks @rstjames for clarifying. Sincerely,  I like both, but if  I have to select one, then the first one

**Comment by aeiras** [comment]
Cute, I also like the 1st one, Emerson! :)

**Comment by Emily-Jiang** [comment]
I like the 2nd one :) as the folded corner is more visible.

**Comment by emecas** [comment]
Following your latest indications @rstjames ( to be printed on t-shirts normally ) I have prepared this version:

![one-color-logo-Emerson-latest](https://user-images.githubusercontent.com/849502/130090600-09275825-7d27-4848-a841-28eee12a4897.png)

What do you think?

**Comment by rstjames** [comment]
@emecas This will not work. The fold you have has many little dots. It will not work for a one-color print on t-shirts or smaller sizes.  That is why I made the example options the way I did. 

If you want to rise your exact design please adjust the fold area.
![Screen Shot 2021-08-19 at 5 14 38 PM](https://user-images.githubusercontent.com/12132146/130094979-0fb7015b-ae44-4cc8-9911-c66a92a45140.png)

**Comment by aeiras** [comment]
MP can choose a TCK compatible logo based on the submissions but not as part of the trademark program.
[[microprofile-wg] [BALLOT] Replace MicroProfile Compatibility Logo with.pdf](https://github.com/microprofile/microprofile-wg/files/7551145/microprofile-wg.BALLOT.Replace.MicroProfile.Compatibility.Logo.with.pdf)
