### ISSUE TITLE
[MP Compatibility Logo Submission] Versions from AJUG

### ISSUE THREAD

**Issue by vincentmayers** [microprofile/microprofile-wg#82]
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG1_1](https://user-images.githubusercontent.com/5480295/117089254-ee185f00-ad22-11eb-8618-d0eb8778a259.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG1_2](https://user-images.githubusercontent.com/5480295/117089255-ee185f00-ad22-11eb-8d2f-9d14391d6f09.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG1_3](https://user-images.githubusercontent.com/5480295/117089256-eeb0f580-ad22-11eb-9c3c-cba1a6acd8ac.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG2_1](https://user-images.githubusercontent.com/5480295/117089258-eeb0f580-ad22-11eb-89bb-36c30293e976.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG2_2](https://user-images.githubusercontent.com/5480295/117089260-ef498c00-ad22-11eb-96ad-ddba9ea7d909.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG2_3](https://user-images.githubusercontent.com/5480295/117089261-ef498c00-ad22-11eb-85ad-52e5da5b4e0f.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG3_1](https://user-images.githubusercontent.com/5480295/117089262-ef498c00-ad22-11eb-80e2-53cc9cc50c8f.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG3_2](https://user-images.githubusercontent.com/5480295/117089263-ef498c00-ad22-11eb-9659-8d45ade84363.png)
![MicroProfile Compatible Logo Comps_MicroProfile Compatible AJUG3_3](https://user-images.githubusercontent.com/5480295/117089264-efe22280-ad22-11eb-9c4b-ed50f68ef72c.png)

**Comment by vincentmayers** [comment]
added drive link

**Comment by aeiras** [comment]
💪🏼 Leave ticket open 💛to enable review work after the 16th!

**Comment by rstjames** [comment]
@vincentmayers  Cool designs. The only issue is that this goes against the branding/ usage of the M in the logo. It is standard not to change, angle or overlap a logo or logo mark. I know we do not have the manual now to explain this but it in is progress: https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:36dbb40b-eb90-49a7-80c6-1ca8074a0dc3

**Comment by rstjames** [comment]
@vincentmayers

**Comment by aeiras** [comment]
Hola Vince @@vincentmayers, 

Please check the latest update on running logos [here](https://github.com/microprofile/microprofile-wg/issues/38)

You are most welcomed to adjust your submission as recommended on May 5th if you desire it.
