### ISSUE TITLE
MicroProfile 4.1 Release Review

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-wg#86]
- [x] Specification name and version
- [x] Add the label `Release Review`
- [x] Naming conventions for artifacts:
   - [x] Specification PDF in the form of microprofile-_project_-spec-_version_.pdf
   - [x] Specification HTML in the form of microprofile-_project_-spec-_version_.html
   - _project_ is the microprofile specification short project name (config, health, ...)
   - _version_ is the two digit x.y version of the specification
<p>

- [x] The Nexus Staging links (orgeclipsemicroprofile-NNNN where NNNN is the staging repository id) (eg, https://<i></i>oss.sonatype.org/content/repositories/orgeclipsemicroprofile-NNNN/org/eclipse/microprofile/config/) which contain all the binaries and relevant documentation:
   - [x] [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile/4.1/)
   - [x] [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile-spec/4.1/microprofile-spec-4.1.pdf)
   - [x] [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile-spec/4.1/microprofile-spec-4.1.html)
   - [x] [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile/4.1/microprofile-4.1-javadoc.jar)
   - [ ] ~~API Jar~~ (Not applicable: the platform release does not provide any additional APIs)
   - [ ] ~~TCK Jar~~ (Not applicable: the platform release does not provide any additional APIs)
<p>

- [x] A link in the Eclipse downloads sections is still available for specs and apidocs:
   - [x] https://download.eclipse.org/microprofile/staging/microprofile-4.1/
   - [x] An apidocs directory containing the javadoc associated with the API jar. (Note: the platform release does not provide an API JAR)
<p>

- [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [x] [Compatible Certification Request](https://github.com/microprofile/microprofile-wg/issues/95)
<p>

- [x] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Follow [governance process](https://projects.eclipse.org/projects/technology.microprofile/governance) and create/update release record
    - [Component Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/4.1)
  - [x] [Email to PMC](mailto:technology-pmc@eclipse.org) (more info [here](https://docs.google.com/document/d/1DFuh3rINWAZQpHpXnB_QM02tAXlI4KwbLjVBk9rX9HA/edit))
  - [x] Start release review by [emailing EMO](mailto:EMO@eclipse-foundation.org) (more info [here](https://docs.google.com/document/d/1euy5ezuSpa6Xn4qV7MTXCWCMJIn16GYiiO-U7H6R-1w/edit))(Track the [bug issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/49) created by EMO after the email) 
  - [x] A member of Steering Committee initiates the ballot by sending an email to [microprofile-wg] (mailto:microprofile-wg@eclipse.org) (more info [here](https://docs.google.com/document/d/1ivzeL4mdqZPwyQR6e5GtCv81F_ZfLOpsg8FaZUoDDuc/edit#heading=h.6e35ro9vzyji)
   - [x] After the voting has ended, email [microprofile-wg] (mailto:microprofile-wg@eclipse.org) with the ballot result (more info [here](https://docs.google.com/document/d/1wISp-yRzQZNOHULNekxxg1U18be3v-3CRUswklcpmr8/edit)

**Comment by kwsutter** [comment]
>     * ~An apidocs directory containing the javadoc associated with the API jar.~ (Not applicable: the platform release does not provide any additional APIs)

But, it seems that the MP Platform does provide an uber javadoc jar file.  So, why not expand that into the 'apidocs' directory for easier viewing?

**Comment by kwsutter** [comment]
Two different directory structures are being used for the spec (pdf and html) and the javadoc?  Why?  Very confusing...

- https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile-spec/4.1/ 
- https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1481/org/eclipse/microprofile/microprofile/4.1/

**Comment by ederks85** [comment]
@kwsutter I think it's a good idea to look at the project's structure in order to fix the confusing locations. I will keep that in mind for the next release

**Comment by radcortez** [comment]
This is because the javadoc generation and the spec are in separate maven projects. We can probably merge them and have them in the same GAV.
