### ISSUE TITLE
MP 4.1 alignment on Jakarta EE 8

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-wg#87]
MP 4.1 contains a description on how MP builds/aligns/relates on or to Jakarta EE 8. The right wording is necessary to be used here. Please provide suggestions.

**Comment by ederks85** [comment]
John Clingan has already provided suggestions via: https://github.com/eclipse/microprofile/pull/217#issuecomment-861589085

BTW, before we go final, I'd like to modify one statement. MicroProfile is not based on Java EE or Jakarta EE, but it does align with some specifications. More specifically:

"MicroProfile 4.1-RC1 is based on Jakarta EE 8. Although Jakarta EE 8 is API backwards compatible with Java EE 8, Jakarta EE replaces Java EE dependencies with Jakarta EE dependencies for all MicroProfile specifications."

should be changed to:

"MicroProfile 4.1-RC1 aligns with the CDI 2.0, JAX-RS 2.1, JSON-P 1.1, JSON-B 1.0, and Annotations 1.3 specifications released with Jakarta EE 8, which are backward-compatible with their Java EE 8 equivalents."

Alternatively, we could simply list the specifications:

"MicroProfile 4.1-RC1 aligns with Jakarta Contexts and Dependency Injection 2.0, Jakarta Annotations 1.3, Jakarta RESTful Web Services 2.1, Jakarta JSON Binding 1.0, and Jakarta JSON Processing 1.1.".

Additional suggestions are welcome.

**Comment by ederks85** [comment]
This builds on the changes made in: https://github.com/eclipse/microprofile/pull/215

**Comment by aeiras** [comment]
+1 to description 2. Let's consciously drop the usage of abbreviations when documenting stuff!

**Comment by ederks85** [comment]
PR created with description 2 as the proposed wording. Feel free to provide any other suggestions.

https://github.com/eclipse/microprofile/pull/219

**Comment by ederks85** [comment]
https://github.com/eclipse/microprofile/pull/219 has been merged
