### ISSUE TITLE
[Trademark & Compatibility] Git issue template to get listed as a Compatible Product

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#89]
Paul offered to provided the Jakarta EE template. Thanks Paul.

**Comment by paulbuck** [comment]
See [https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md](url)

**Comment by aeiras** [comment]
Hola Paul, 
The link gives me a 502 Bad Gateway. thanks for verifying it.

**Comment by paulbuck** [comment]
I fixed it up, try now.

**Comment by aeiras** [comment]
It works, Paul. Gracias! :)

**Comment by aeiras** [comment]
in place!
