### ISSUE TITLE
[marketing] Documentation on how to perform a PR in any mp repository

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-wg#92]
Documentation about the requirements and how to submit a first PR for MicroProfile is missing in the website and also on this repo. 

I created https://github.com/microprofile/microprofile-wg/pull/91 as a reference we made with the community in https://github.com/jakartaee/collateral/blob/master/docs/how-to-pr.adoc

But ultimately I would vote for this information to reach the public-facing website https://microprofile.io/contributors/ or under https://microprofile.io/resources/

**Comment by aeiras** [comment]
@cesarhernandezgt, thank you for such a wonderful contribution. I have added a request directly on the PR comments. 
Once you help us link the document to the Contributing doc, the information will be linked under the Contributors tab. 
We need a separate git issue from you to add to the Resources Page.

**Comment by aeiras** [comment]
@nsardana-bny 
I am taking the liberty to add you in this ticket b/c it deals with merging documentation PRs, pages and wikis. 

https://github.com/eclipse/microprofile-marketing/issues/469  this ticket relates to current documentation that needs to become a Page under the [Mktg repo ](https://github.com/eclipse/microprofile-marketing/wiki)

Let's use the actual 469 ticket to unblock you if you encounter any issues with the creation of the page in that space. 
Thank you, MicroProfiler.

**Comment by debbiehoffman** [comment]
Hi all,
 Just checking if this documentation has been added to the website yet? I did not see it here https://microprofile.io/contributors/ or under https://microprofile.io/resources/

**Comment by aeiras** [comment]
wow, @debbiehoffman, you got the 1 item (add to the Resources page) missing back on track!!!!

Cesar committed a PR to the Contributors landing page linked in MP by Become a MicroProfiler By button. 
[Become a MicroProfiler](https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc)
With do a Pull Request guidelines: 
![image](https://user-images.githubusercontent.com/10731224/136860639-3efa524b-80ab-46a4-96b6-f9ff7f361246.png)


Now, we need to also add the how, PR link https://github.com/eclipse/microprofile/blob/master/how-to-pr.adoc to Resources in the website. Or what other idea should that document go into? 

Thank you for being amazing at tracking stuff, Debbie!

**Comment by aeiras** [comment]
@rstjames, 

Can you add to Resources  Cesar's contribution wiki on How to Create a PR - Learn ?

Thank you,

**Comment by rstjames** [comment]
@aeiras on the dropdown menu? or on the WG page tabs?

**Comment by rstjames** [comment]
Updated
