### ISSUE TITLE
The draft MicroProfile Trademark Guidelines doc format

### ISSUE THREAD

**Issue by paulbuck** [microprofile/microprofile-wg#93]
The draft MicroProfile Trademark Guidelines is a Microsoft Word doc, can that one be converted to a google doc please? 

https://docs.google.com/document/d/1dturdVLQvx-UV6TbD9wr0pgFReBXhDH0/edit?pli=1

I and I expect that others do not have access to Microsoft Office and using G Suite to edit and comment on a Microsoft Office document is not always reliable.

**Comment by aeiras** [comment]
Sure Paul. 
I will ask the contributor who lead the work to do the conversion.

**Comment by paulbuck** [comment]
Thanks so much!

**Comment by kwsutter** [comment]
> I will ask the contributor who lead the work to do the conversion.

Even though it is a .docx type on the file, everything with posting comments and/or editting seems to work just fine.  If we want to change the type on it, then all current references will need to be updated.  Unless there is a direct issue with this .docx format, I would suggest that we just leave it as-is until it becomes ready to be cast into stone.

@paulbuck are you okay with this approach?  Or, have you experienced problems with this .docx format?

Thanks!

**Comment by paulbuck** [comment]
Hi Kevin,

I think I was having a bad day yesterday w/ the G Suite + MS Office .docx
experience. Appears to be better today, so let's leave it as-is for
the reasons you mentioned.

Thanks ... Paul

**Comment by aeiras** [comment]
@paulbuck, 

[[microprofile-wg] [BALLOT] Replace MicroProfile Compatibility Logo with.pdf](https://github.com/microprofile/microprofile-wg/files/7551052/microprofile-wg.BALLOT.Replace.MicroProfile.Compatibility.Logo.with.pdf)
Given the vote passing, what do we need to do to complete the Guidelines? 

There is nothing missing from the side of MP. 

Thanks for the follow up,
