### ISSUE TITLE
2022 MPWG Program Plan

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-wg#99]
Oct 2nd thread with call to action lands in the Community forum via John. 

Program plan: https://docs.google.com/presentation/d/1jX1YfeOEN_k60voVj9CVGwT7yXvlF8NA/edit#slide=id.p1
Deadline: Candidate Program Plan Approved by Steering Committee (Due November 5, 2021)

Budget plan: https://docs.google.com/spreadsheets/d/100jj5LL0VLZIChrDmptFSRuCau5MKyCkW90QSlDEfW0/edit#gid=950497108

Deadline: Final Budget reviewed and approved by Steering Committee (Due November 19, 2021)

2021 MPWG Plan and Budget listed under MPWG page 
https://microprofile.io/workinggroup/

**Comment by aeiras** [comment]
Program plan went for a vote today with a 7 day ballot https://www.eclipse.org/lists/microprofile-wg/msg01171.html

**Comment by TetianaFTV** [comment]
Approved https://www.eclipse.org/lists/microprofile-wg/msg01171.html
